### DISCUSSION TITLE
How to make menu button not clickable in Jekyll

### DISCUSSION THREAD

**Discussion by rndwork** [jekyll/jekyll#8838] [Q&A]
Hi there!

The question is related to the menu building. As for now menu is identified in file menus.yml located in _data folder. The structure is the following:
```
main:
  - name: "page1"
    url: "/page1/"
    sublinks:
    - name: name1
      url: url1.html
      icon: <svg width="32" height="32"... </svg>
      desc: descr1
    - name: name2
      url: url2.html
      icon: <svg width="32" height="32"... </svg>
      desc: descr2
  - name: "page2"
    url: "/page2/"
```
I need to make page1 button not clickable as there won't be any page. The idea is to hover on page1 and see the list of sublinks that are clickable (the link of the page1 should be not clickable). If I am simply removing url: "/page1/" the page is still clickable, but it doesn't redirect me to anywhere.
Can I somehow disable clicks on this button at all?
