### DISCUSSION TITLE
Fixing Liquid Exception: incompatible character encodings: Windows-1252 and UTF-8

### DISCUSSION THREAD

**Discussion by Schallbert** [jekyll/jekyll#9089] [Show and tell]
An issue with a very similar title had been opened years ago [here](https://github.com/jekyll/jekyll/issues/7581#issue-423431011) but wasn't maintained. I just experienced the very same error message
`Liquid Exception: incompatible character encodings: Windows-1252 and UTF-8 in /_layouts/default.html`
that I didn't find very helpful.

Root cause was that in one of my posts I forgot to add the front matter like 
```yaml
---
title: "Jekyll: images"
excerpt: "Why some images display OK locally but won't on Github"
header:
  teaser: [...]
  [...]
```

Making sure this is correctly added fixed the issue for me.
