### DISCUSSION TITLE
Restoring missing gems when running Jekyll in Docker

### DISCUSSION THREAD

**Discussion by mu88** [jekyll/jekyll#9180] [Q&A]
I'm trying to run my GitHub Page which is using Jekyll locally on my Windows machine ([code of my page](https://github.com/mu88/mu88.github.io/)).

The Jekyll config `_config.yml` references the following plugins:
```yaml
# all the other Jekyll settings

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
```

I follow the [official manual][1] from [here][2] and created the following `docker-compose.yml`:
```yaml
version: '2.2'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: >
      sh -c "gem install jekyll-seo-tag jekyll-sitemap jemoji &&
             jekyll build &&
             jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
```

As you can see, at first I have to manually install all dependencies (which are specified in the `plugins` section of `_config.yml`).

When reducing the `command` to `jekyll serve` (as described [in the docs][3]), the following error occurs:
```
mu88githubio-jekyll-1  | ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
mu88githubio-jekyll-1  | Configuration file: /srv/jekyll/_config.yml
mu88githubio-jekyll-1  |   Dependency Error: Yikes! It looks like you don't have jekyll-seo-tag or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-seo-tag' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
mu88githubio-jekyll-1  | jekyll 3.8.6 | Error:  jekyll-seo-tag
mu88githubio-jekyll-1 exited with code 1
```

[The docs][4] also mention the command `bundle update`, but this gives me:
```
mu88githubio-jekyll-1  | Could not locate Gemfile
mu88githubio-jekyll-1 exited with code 10
```

What bothers me with my current "solution" is that I have to specify the dependencies/plugins twice, both in `docker-compose.yml` and `_config.yml`.

Is it possible to get rid of this redundancy and make the Jekyll Docker image restore the necessary gems automatically when using `jekyll serve` and using `_config.yml`?

Thanks and have a great weekend!

PS: I've also placed [this question](https://stackoverflow.com/questions/74327350/restoring-missing-gems-when-running-jekyll-in-docker) on Stack Overflow last weekend, unfortunately no answers yet.

  [1]: https://github.com/envygeeks/jekyll-docker/blob/master/README.md
  [2]: https://hub.docker.com/r/jekyll/jekyll/
  [3]: https://github.com/envygeeks/jekyll-docker/blob/master/README.md#usage-3
  [4]: https://github.com/envygeeks/jekyll-docker/blob/master/README.md#updating

**Comment by pranabdas** [comment]
Could you try adding `Gemfile` in your project root with following content (also remove `Gemfile.lock` if exists):
```
source "https://rubygems.org"

gem "github-pages"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jemoji"
end
```

Then you run this command once:
```
bundle config set --local path 'vendor' && bundle install
```

The gems will be installed in a folder named `vendor` locally. Remember to include it in `.gitignore` so that you don't include in your git history. If you delete this folder, you need to run above command again.

Now you should be able to serve your site locally by:
```
bundle exec jekyll serve
```

**Reply by mu88** [reply]
Great, that works, thank you 💪🏻

However, now the process logs that 92 gems were downloaded and installed. I'm wondering why this is necessary because with my previous approach, only the three missing gems were downloaded and installed - I assume the other 89 gems are already a part of the Docker image `jekyll/jekyll`.  
Can this be optimized, i. e. download only the missing 3 gems and use the other ones from Docker?

**Comment by pranabdas** [comment]
Your project depends on more than the listed plugins (I got error while doing quick check). So, I used the [`github-pages`](https://github.com/github/pages-gem) gem, which includes all common (jekyll related) dependencies. In your case following `Gemfile` spec should be enough:
```
source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jemoji"
end
```
Delete `Gemfile.lock` and `vendor` folder from your project if exists. Run `bundle install` followed by `bundle exec jekyll serve`.

**Reply by mu88** [reply]
Here is my `docker-compose.yml`:
```yaml
version: '2.2'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: >
      sh -c "bundle install &&
             bundle exec jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
```

And the `Gemfile`:
```ruby
source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jemoji"
end
```

But it still logs `Bundle complete! 4 Gemfile dependencies, 42 gems now installed.`, whereas my previous version (with the duplicates) only downloads the four missing gems and logs `4 gems installed`
