### DISCUSSION TITLE
Changing the Permalink for Posts

### DISCUSSION THREAD

**Discussion by marsfan** [jekyll/jekyll#9399] [Q&A] [answered]
I've been enjoying working with jekyll, but I don't rellay like the permalink format for posts (`YYYY/MM/DD/TITLE.html`) and would prefer for it to be something simpler, such as just `blog/TITLE.html`

Is it OK to change the permalink path for the posts collection? I've seen some stuff online saying that it is not possible, but when I add the following snippet to my `_config.yml`, it seems to properly change the permalink format to what I want. 

```yaml
collections:
  posts:
    output: true
    permalink: /blog/:title
```
