### ISSUE TITLE
Clean up and simplify main.css

### ISSUE THREAD

**Issue by wbzyl** [jekyll/jekyll#1316]
1. These declarations:

``` css
body {
  font: 13.34px Helvetica, Arial, sans-serif;
  font-size: small;
}
```

browsers simplify to:

``` css
body {
  font: small Helvetica, Arial, sans-serif;
}
```

What about enlarging font size to the default size:

``` css
body { font-family: Helvetica, Arial, sans-serif; }
/* and remove .site {  font-size: 115%; } */ 
```

2.  Remove:

``` css
table {
  font-size: inherit;
  font: 100%;
}
```

These declarations are superfluous, I think.

3. The _display_ declaration could be removed too:

``` css
.site .header h1.title {
  display: inline-block;
}
```

--Włodek Bzyl
