### ISSUE TITLE
A collection from _config.yml cannot be filtered with {{ | map: }}.

### ISSUE THREAD

**Issue by varya** [jekyll/jekyll#1620]
Liquid templates fall when filtering a collection with a string.
I have a collection defined in _config.yml, e.g

```
site:
    name:
        en: 'Site name in English'
        ru: 'Site name in Russian'
```

When creating an ouput site.name.en works fine, but `{{ site.name | map: 'en' }}` gives this error:

Liquid Exception: can't convert String into Integer in <filename here>

This starts after updating to Jekyll 1.2.1. As GitHub already updated Jekyll to this version, none of those users who had such `{{ | map: }}` things cannot update their blogs.

Could you please fix it a.s.a.p. or offer any workaround besides replacing this structures with cycles?
