### ISSUE TITLE
jekyll yml parse

### ISSUE THREAD

**Issue by akulubala** [jekyll/jekyll#1744]
Hi ，
i build a yml attribuit like this:

``` yaml
links:
- title: Code
    url: /about
    sub_catogory:
        -a: PHP
          b:/php
        -a: Ruby
          b:/ruby 

- title: MYSQL
    url: https://github.com/url
    external: true
    sub_catogory:
        -a: PHP
          b:/php
        -a: Ruby
          b:/ruby 
```

and i want retrieve it for a category list:

``` html
   <li id="category" >
              <a href="{{ site.url }}" title="{{ site.title }}">Category</a>
              <ul style="display: block;">
                {% for link in site.links %}
                <li>
                    <a href="{{ link.url }}" >{{ link.title }}</a>
                    <ul class="sub_category">
                        {% for subcategory in link.sub_catogory %}
                        <li><a>{{ subcategory.a }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %} 
              </ul>
   </li>
```

thanks for your help!
