### ISSUE TITLE
Allow excluding files in _posts

### ISSUE THREAD

**Issue by amitaibu** [jekyll/jekyll#1758]
I'm trying to work on incremental builds, and tried to add to my _config.yml:

``` yaml
exclude: ['_posts']

# Include only the a specific post.
include: ['_posts/2013-1-1foo.html']
```

However it seems that excluding `_posts` doesn't work
