### ISSUE TITLE
excerpt_separator ignored when using redcarpet markdown

### ISSUE THREAD

**Issue by mikechambers** [jekyll/jekyll#1839]
When setting markdown to be redcarpet, the excerpt_separator property is ignored. Excerpts are not created at the separator, and the separator is included in the posts.

If you change the markdown engine to maruku excerpt_separator works as expected.
- Mac OS X 10.9
- jekyll 1.4.2
- redcarpet (3.0.0, 2.3.0)

_config.yaml

``` yaml
name: Your New Jekyll Site
markdown: redcarpet
pygments: true

excerpt_separator: <!--more-->
```

post.markdown

``` yaml

---
layout: post
title:  "Welcome to Jekyll!"
date:   2013-12-17 13:11:14
categories: jekyll update

---

You'll find this post in your `_posts` directory - <!--more-->edit this post and re-build (or run with the `-w` switch) to see your changes!
To add new posts, simply add a file in the `_posts` directory that follows the convention: YYYY-MM-DD-name-of-post.ext.

Jekyll also offers powerful support for code snippets:

Just some more stuff.
```
