### ISSUE TITLE
Pagination only working offline

### ISSUE THREAD

**Issue by vdecree** [jekyll/jekyll#1840]
Hi there,

I've been playing around with Jekyll and locally everything works fine. However once pushed to Github and run from Gitpages, the pagination for my posts page doesn't work properly. It's paginating the page. I get a next arrow, but once clicked you stay on the same page, so i guess it's not generating the pages correctly.

My config looks like:

``` yaml
name: Sitename
description: "A description of your site"

root: /
permalink: /blog/:year/:month/:day/:title
markdown: redcarpet
pygments: true

paginate: 8          # Posts per page on the blog index
paginate_path: "blog/page:num"

navigation:
- text: Posts
  url: /posts/
- text: Archive
  url: /archive/
- text: About
  url: /about/
```

I've tried a number of different settings, but nothing works. Locally like i said, works fine. It's generating the pages upon`jekyll build` command. 

My blog.html

``` html
<div class="posts">
    {% for post in paginator.posts %}
    <div class="post-listing">
        <h2><a class="post-title" href="{{ post.url }}">{{ post.title }}</a> </h2>
        <p class="meta"><time class="pubdate updated" datetime="{{ post.date }}" itemprop="dateCreated">{{ post.date | date: "%-d %B, %Y" }}</time></p>
        <span class="post-e">{{ post.excerpt }}</span>
    </div> <!-- end post -->
    {% endfor %}
</div>

<div class="pagination">
  <ul>
  {% if paginator.previous_page %}
    <li class="previous">
      {% if paginator.previous_page == 1 %}
        <a href="/blog/">&larr; Prev</a>
      {% else %}
        <a href="{{ paginator.previous_page_path }}">&larr; Prev</a>
      {% endif %}
    </li>
  {% else %}
    <li class="previous disabled">
      Prev
    </li>
  {% endif %}


  {% if paginator.next_page %}
    <li class="next">
      <a href="{{ paginator.next_page_path }}">Next &rarr;</a>
    </li>
  {% else %}
    <li class="next disabled">
      Next
    </li>
  {% endif %}
  </ul>
</div><!-- .pagination -->
```
