### ISSUE TITLE
Colons in metadata make Jekyll sad

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jekyll#2030]
Consider this metadata:

``` yml

---
 description:
   We are conducting research with developers at: large companies, small companies, and individuals with side projects.
 ---
```

Generating this file throws the following error:

```
      Generating...   Liquid Exception: undefined method `to_str' for #<Hash:0x0000010f4535c0> in _includes/_post.html, included in categories/research/index.html
```

See the problem? The `developers at:` portion appears to be another YAML hash for Jekyll, but it isn't at all!

I'm not sure if we can legitimately escape all colons. Is there a way we can fix this, though?
