### ISSUE TITLE
Add some way of changing default tag properties

### ISSUE THREAD

**Issue by 0xcaff** [jekyll/jekyll#2241]
Say I have a blog and I would like to markup all `<code>` tags with the [code schema.](http://schema.org/Code) I could do this in JavaScript but that would defeat the whole point of jekyll. It would be nice if there was some way to set default properties for tags.

There are many ways to implement this but here is my approach:
in the config file add a property called `tags`. When building the site, loop over all the elements in tags and add the attributes under each tag. For our code example:

**config**

```
# ...
tags:
  code:
  - itemscope
  - itemtype: code
# ...
```

would translate all `<code>` to:

```
<code itemscope itemtype="code"></code>
```

modifying html and text would be cool too:

```
tags:
  code:
  - html: "<p>this html will replace all html in code tags</p>" # this will replace
  - html<: "<p>this html will be appended to code tags</p>" # this will append
  - html>: "<p>this html will be prepended to code tags</p>" # this will prepend

  # similar text properties
```

selectors:

```
tags:
   code:first: # selects the first code in page
     #properties
```

nested selectors:

```
tags:
  div:
    code:
```

etc.
