### ISSUE TITLE
_config.yml 'defaults:' doesn't work for permalink

### ISSUE THREAD

**Issue by edj-boston** [jekyll/jekyll#2280]
I've tried this on Jekyll `1.4.3` and `1.5.1`. I have Ruby version `ruby 2.0.0p247 (2013-06-27 revision 41674)` installed. I'm on a mac using this command to preview my site:

```
jekyll serve --watch
```

I want my permalink setting to be "post"-specific. but it doesn't work

Doesn't work:

``` yml
markdown: redcarpet
defaults:
  -
    scope:
      type: "post"
    values:
      permalink: /:categories/:title
```

Works (but is too general):

``` yml
markdown: redcarpet
permalink: /:categories/:title
```

**Comment by ibc** [comment]
jekyll 3.1.2

This produces the expected result:

```yaml
permalink: pretty

defaults:
  -
    scope:
      path: ''
    values:
      layout: layout
```

However this:

```yaml
defaults:
  -
    scope:
      path: ''
    values:
      layout: layout
      permalink: pretty
```

generates a ugly `_site/pretty.html` file...
