### ISSUE TITLE
Set permalinks "pretty" for collections?

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll#2293]
In Jekyll 2.0.0.rc1

For _config.yml I have 
`permalink: pretty`

I would think that this setting would be respected throughout the site, including collections but my collections documents end with a ".html" extension while posts and pages render as expected.

I also tried:

```
collections:
  books:
    output: true
    permalink: pretty
```

But this didn't change anything. I don't know Ruby, but I was comparing the collection.rb file to the page.rb and didn't see the same references vis-à-vis permalinks.
