### ISSUE TITLE
Setting category in _config.yml is not picked up by permalink

### ISSUE THREAD

**Issue by tschmidt** [jekyll/jekyll#2343]
I've been messing around with how to add a category to my posts recently. The first thing that I did was to set the permalink in my `_config.yml` file like this:

```
...
permalink: /:categories/:title.html
...
```

Then, in my posts YAML front matter, I set the category:

```

---
category: 'article'

---
```

When I run `jekyll build` I get the site structure I would expect:

```
_site
|- article
  |- my-first-post.html
```

Since I want to use `article` as the default and only change it when I need to, I thought I could set the configuration option in my `_config.yml` file like this:

```
defaults:
  -
    scope:
      path: ''
      type: 'post'
    values:
      category: 'article'
permalink: /:categories/:title.html
```

When I run `jekyll build`, I get a site structure like this:

```
_site
|- my-first-post.html
```

Is this the expected behavior? Do I need to specify the category on a post by post basis?
