### ISSUE TITLE
List of collections not rendering

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#2346]
I am trying to build a list of the collections I have defined in my _config.yml, thus:

``` yaml
collections:
  articles:
    output: true
    title: Articles
  essays:
    output: true
    title: Academic Essays
  presentations:
    output: true
    title: Presentations
  projects:
    output: true
    title: Projects
```

using the following Liquid template:

```
{% for collection in site.collections %}
    <section>
        <h1><a href="{{ collection.directory }}">{{ collection.title }}</a></h1>
        Label: {{ collection.label }}
    </section>
{% endfor %}
```

but the following is rendered:

```
<section>
    <h1><a href=""></a></h1>
    Label: 
</section>
<section>
    <h1><a href=""></a></h1>
    Label: 
</section>
<section>
    <h1><a href=""></a></h1>
    Label: 
</section>
<section>
    <h1><a href=""></a></h1>
    Label: 
</section>
```

The [documentation](http://jekyllrb.com/docs/collections/) says:

> …collections are also available under `site.collections`, with the metadata you specified in your `_config.yml`…

Is what I’m attempting correct? Or is this a bug?

Thanks—and congratulations on shipping v2!
