### ISSUE TITLE
Defaults precedence doesn't seem to work

### ISSUE THREAD

**Issue by feuerbach** [jekyll/jekyll#2371]
I'm using jekyll from recent git master (8cad40a124de7e28dc199948ecf416893458b4bc).

I have the following defaults block in `_config.yml`:

```
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"
```

However, it looks like the `page` layout is applied to posts, too.
