### ISSUE TITLE
Frontmatter defaults not working for posts subdirectory

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll#2372]
I've tried to setup frontmatter defaults for _all files_ (get `layout: default`), _all posts_ (get `layout: post`) and _portfolio posts_ (get `layout: post--portfolio`).

The first two things work, but I the last layout default isn't applied. I'm not sure, but shouldn't this apply to all files under `_posts/portfolio`? Sorry, if I'm missing something.

```
defaults:
  -
    scope:
      path: "" # all files have the `default` layout
    values:
      layout: "default"
  -
    scope:
      path: "" # all posts have the `post` layout
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: "portfolio" # all posts under `portfolio` have the `post--portfolio` layout
      type: "post"
    values:
      layout: "post--portfolio"
```
