### ISSUE TITLE
Sass/SCSS Assets Compilation Respects Frontmatter Defaults

### ISSUE THREAD

**Issue by jaybe-jekyll** [jekyll/jekyll#2402]
When performing Sass/SCSS assets compilation, combined with global-type front matter defaults set, assets compilations respect and apply front matter defaults.

For example:

With Frontmatter defaults such as the following set, Sass/SCSS assets compilations are inheriting and applying said Frontmatter `layout` defaults:

> config.yml

``` yaml
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
```

Front matter defaults settings provide for optional exclusion by type (page, post or draft).

Should front matter defaults apply to Sass/SCSS assets compilation?

> assets/css/style.scss

``` scss

---

---

html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline; }
```

> Resulting assets build output at assets/css/style.css

``` html
<!--This is _layouts/default.html-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="/assets/css/style.css">
  </head>
  <body>
    html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline; }

...
```
