### ISSUE TITLE
Jekyll in the github pages can compile SASS?

### ISSUE THREAD

**Issue by agassiyzh** [jekyll/jekyll#2404]
``` yml
sass:
  sass_dir: css
  style: :compressed
```

I launch with command`jekyll server --safe`,it can work fine.But in in the github page, it looks like the server do not compile the sass file.

My respository: https://github.com/agassiyzh/agassiyzh.github.io

So, waht the version of jekyll be used in the github pages server.

_Sorry for my poor English._

Thx for your help.
