### ISSUE TITLE
Front-matter defaults in collections

### ISSUE THREAD

**Issue by jens-na** [jekyll/jekyll#2405]
Front-matter defaults are available since #2205 and collection support is enabled since #2199, but unfortunately front-matter default values for collections are not implemented.

This is my initial implementation proposal for that.
#### Implementation

Create a new "defaults scope" named `collection`.

_config.yml example:

``` yml
name: test
markdown: redcarpet
highlighter: pygments

collections:
  slides:
    output: true

defaults:
  -
    scope:
      collection: slides
    values:
      test: "foo"
      test2: "bar"
```

The values `test` and `test2` are only available in files which belong to the `_slides` collection.

_slides/example-slide.html:

``` html

---
layout: slide
title: Example

---
<html>
  <h1>{{ page.test }}</h1>
</html>
```

Any ideas/opinions?
