### ISSUE TITLE
Collections ignoring permalink settings

### ISSUE THREAD

**Issue by mattes** [jekyll/jekyll#2407]
I would expect that the following in my `_config.yml` ...

```
collections:
  blog:
    output: true
    permalink: pretty
  docs:
    output: true
    permalink: pretty
```

... produces:

```
$ tree
.
├── 2014
│   └── 05
│       └── 15
│           └── hello-world
│               └── index.html
```

but it seems as if it ignores the `permalink` setting and produces:

```
$ tree
.
├── 2014-05-15-hello-world.html
```

[full dir structure](https://gist.github.com/mattes/25b8b6ad693059d20975)

Am I doing sth wrong?
