### ISSUE TITLE
Date doesn't work in front matter defaults

### ISSUE THREAD

**Issue by svetlanapuro** [jekyll/jekyll#2422]
Hi there,
I want my posts to be the same date. So I put the following in my _config.yml file:

```
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      date: "31.05.2014"
```

But when I build the site, instead of the date specified in front matter defaults, the posts get the date specified in the names of the files initially. Although when I add the date manually to the front matter of each post, it works.

I also tried to put the date in a different format like `date: 2014-05-31`, but it still doesn't work.

So can I set the date in front matter defaults? If yes, how can I do it?

**Comment by iloveip** [comment]
Hello @jens-na 

I have a question. When I set a custom variable for update date in front matter defaults for all posts it works. For example:

````
# Defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
      update: "2015-01-31"
````

But when I set it for posts with specific path like this it doesn't:

````
# Defaults
defaults:
  -
    scope:
      path: "kb"
      type: "posts"
    values:
      permalink: /kb/:title/
      update: "2015-01-31"
````

Do you know why this can happen?
