### ISSUE TITLE
Liquid in SCSS

### ISSUE THREAD

**Issue by rnkn** [jekyll/jekyll#2692]
Unless I'm missing something, the following SCSS should work:

``` scss

---
layout: none

---

body {
    background-image: url({{ "/background.jpg" | prepend: site.assets_url }});
}
```

but it results in the error

```
Conversion error: There was an error converting 'css/main.scss'.
jekyll 2.2.0 | Error:  Invalid CSS after "...und-image: url(": expected ")", was "{{ "/background..."
```
