### ISSUE TITLE
“Build Warning: Layout 'nil' requested in atom.xml does not exist.”

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#2712]
I want most of the pages in the root of my site to use the “new” layout, so I have this in my `_config.yml`:

```
defaults:
    -
        scope:
            path: ""
            type: page
        values:
            layout: new
```

Since “new” is an HTML template, though, I obviously don’t want it to be used for e.g. my Atom feed. I included this line in the front matter of `atom.xml`:

```
layout: nil
```

This worked fine in Jekyll 2.0.3. I’m now using Jekyll 2.2.0, and while `atom.xml` seems to be generated correctly, I get errors like these when building the site:

```
Build Warning: Layout 'nil' requested in atom.xml does not exist.
Build Warning: Layout 'nil' requested in index.html does not exist.
```

Is specifying a layout of `nil` not the correct way to indicate that I don’t want a layout to be used for a page? If it is the correct way, errors like this should not be shown.
