### ISSUE TITLE
Front Matter Variables: "Draft" type not recognized?

### ISSUE THREAD

**Issue by rocketspops** [jekyll/jekyll#2726]
In config.yml I have:

```
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "draft"
    values:
      tags: "draft"
  -
    scope:
      path: ""
      type: "post"
    values:
      type: "post"
```

For some reason, I can't get Jekyll to respect the second block. I'm trying to tag all drafts with the tag "draft," but I'm not having much luck. The first and third blocks are working. 

Any ideas?

**Comment by simba4everyoung** [comment]
I had the same problem in Jekyll 3.0.0. 
I want to set default author for drafts. In my _config.yml I have:

```
defaults:
    -
        scope:
            path: "" 
            type: "drafts" 
        values:
            author: Simba Draft
            layout: "post"

    -
        scope:
            path: "" 
            type: "posts" 
        values:
            layout: "post"
```

I tried this, also tried setting posts before drafts. I can't get drafts' author set. All the posts are without author now. 
Is there anything wrong? Or how should I do it?
