### ISSUE TITLE
collections.output: true just copies md files

### ISSUE THREAD

**Issue by jdu** [jekyll/jekyll#2893]
Hey,

Not sure if this is a "need more guidance" problem or a larger issue, trying to use Jekyll 2.3 to build up a bit of a documentation system but have been struggling for a while trying to get collections to work. At this point collections just don't do anything for me. I'm basically trying to get jekyll to do exactly what the jekyll web site does (_docs folder to _docs/path/index.html for each doc), but it's a no go. I can download the jekyll web site source and `jekyll build` will run for it, but the moment I try to set up my own version and run `jekyll build`, it won't work, it just copies the files in _docs exactly (no markdown parsing no liquid) to the same folder in _site, so

_docs/test.md becomes _site/docs/test.md

```
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif

collections:
  docs:
    output: true
```

I'm either missing something that isn't clear in the documentation and needs to be made clearer for collections configuration or there's something really weird going on.

Any help would be appreciated.
