### ISSUE TITLE
Subdirectories in collection rendered but not added to site

### ISSUE THREAD

**Issue by bodokaiser** [jekyll/jekyll#3033]
I am using a collection named `pages` which itself contains directories to various topics:

```
/
  /_layouts
  /_includes
  /_pages
    /cooking
      /pancake.md
    /programming
      /rails.md
```

my `_config.yml' is:

``` Yaml
markdown: redcarpet
permalinks: pretty
highlighter: pygments

title: Studies
baseurl: /

collections:
  pages:
    output: true
    permalink: /:path/index.html
```

The good news first _the markdown files in `_pages/` are rendered_ the bad they do not appear in the `site` variable.

Is there any data I could provide more?
