### ISSUE TITLE
Possible to set a default post title?

### ISSUE THREAD

**Issue by bcomnes** [jekyll/jekyll#3046]
Rather than using the filename as the default title, I would like to use `null`:

``` yaml:
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      title: "null"
```

Right now, it doesn't seem to work.  If thats a modification you are willing to accept, where is a good place to start in the code to make that work?

**Comment by louwers** [comment]
Have you found a more elegant solution to this?

**Comment by louwers** [comment]
I found the more elegant solution, use an empty string as default:
```yaml
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      title: ""
```
then in some cases this works:
```html
    {% if post.title %}
      <h1><a href="{{ post.url | remove: '.html' }}">{{ post.title }}</a></h1>
    {% endif %}
```
weirdly enough, other times you have to use:
```html

        {% if post.title == "" %}
            {{ post.content | strip_html | truncatewords:5 }}
        {% else %}
            {{ post.title }}
        {% endif %}
```
This allows for posting without YAML frontmatter and without titles.
