### ISSUE TITLE
Custom Front Matter values in defaults are not available in templates

### ISSUE THREAD

**Issue by heymarkreeves** [jekyll/jekyll#3072]
The [Front Matter Defaults documentation](http://jekyllrb.com/docs/configuration/#front-matter-defaults) includes an example of setting `author`. This does not actually work, nor do any other custom Front Matter values I try to set.

Here's what my defaults look like:

```
defaults:
  -
    scope:
      path: "news/en"
    values:
      categories: "en news"
      lang: "en"
      layout: "post"
  -
    scope:
      path: "news/fr"
    values:
      author: "mjr"
      categories: "fr news"
      custom_var: "test"
      lang: "fr"
      layout: "post"
```

The only ones that are working are those that are recognized as config options: `categories`, `layout`.

Are custom values not supported in defaults?

I'm running Jekyll 2.4.0.

Thanks!
