### ISSUE TITLE
Liquid Exception: undefined method on windows

### ISSUE THREAD

**Issue by THE-117** [jekyll/jekyll#3078]
Hi Guys !
Do any one have a solution to this issue !
i am using windows
jekyll 2.4.0

``` text
D:\Dev\Awesome>jekyll serve
Configuration file: D:/Dev/Awesome/_config.yml
            Source: D:/Dev/Awesome
       Destination: D:/Dev/Awesome/_site
      Generating...
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:164:
 warning: cannot close fd before spawn
'which' is not recognized as an internal or external command,
operable program or batch file.
  Liquid Exception: undefined method `[]' for nil:NilClass in _posts/2014-11-09-welcome-to-jekyll.markdown
jekyll 2.4.0 | Error:  undefined method `[]' for nil:NilClass
```

My Config.yml:

``` yml

---
# This configuration file contains the absolute path locations of all
# installed Rubies to be enhanced to work with the DevKit. This config
# file is generated by the 'ruby dk.rb init' step and may be modified
# before running the 'ruby dk.rb install' step. To include any installed
# Rubies that were not automagically discovered, simply add a line below
# the triple hyphens with the absolute path to the Ruby root directory.
#
# Example:
#
# ---
# - C:/ruby19trunk
# - C:/ruby192dev
#

---
- C:/Ruby21-x64
# Build settings
highlighter: true
markdown: kramdown
highlighter: pygments
```
