### ISSUE TITLE
Frontmatter defaults not working for files without Frontmatter declared block

### ISSUE THREAD

**Issue by kisenka** [jekyll/jekyll#3107]
I have markdown file test.md on Jekyll's root with the following content: 

``` md
# Test
```

Also defaults section in _config.yml:

``` yml
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
```

After `jekyll build` test.md will be copied in _site directory as is without processing. But if I add Frontmatters block (even without any values), the layout will be applied and file will be converted to HTML.
Is it normal behaviour or bug (Jekyll 2.5.1)?
