### ISSUE TITLE
Permalinks for posts set in YAML Front Matter and Front Matter defaults work differently

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3266]
Hi there,

I would like to change the permalinks style for the posts. When I set `permalink: /kb/:path/` in YAML Front Matter in a post with the file name `2015-01-08-test.md`, the post in shown at `/kb/test/`. But when I set `permalink: /kb/:path/` in Front Matter defaults for all posts,  I get an error that the page can not be found. Here is how my `_config.yml` file looks like:

````
# Permalinks
permalink:          pretty

# Defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
      permalink: /kb/:path/
````

Is this a supposed behavior or am I doing something wrong?

Update: Actually `permalink: /kb/:path/` set in YAML Front Matter in a post also doesn't work. Is there anyway to set this kind of permalinks style for posts?
