### ISSUE TITLE
Front matter defaults for collection's documents in subfolders

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3287]
Hi there,

I would like to organize collection's documents in subfolders and assign them different categories through front matter defaults. I have the following structure:

````
_kb
    - category1
        - article1.md
    - category2
        - article2.md
````

 In my `_config.yml` file I have:

````
# Collections
collections:
  kb:
    output: true
    permalink: /kb/:name/

# Defaults
defaults:
  -
    scope:
      path: "_kb/category1/"
      type: "kb"
    values:
      category: "category1"
  -
    scope:
      path: "_kb/category2/"
      type: "kb"
    values:
      category: "category2"
````

But this doesn't work. Any idea how I can assign different categories to documents in different subfolders through front-matter defaults?

**Comment by Alexander01998** [comment]
I'm running into the same issue with this code:
```YAML
defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      author: "Alexander01998"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
      category: ""
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
      category: "Wurst-update"
    values:
      layout: "post-Wurst-update"
```
I guess it doesn't like multiple defaults with similar scopes.
@parkr, any ideas?

**Comment by miklos-martin** [comment]
I could make use of it as well

**Comment by solygen** [comment]
+1

**Comment by parkr** [comment]
This particular use-case, where categories are assigned based on subfolders, will be handled by #3690 because that's a feature we'll port over. That being said, not sure what's happening here.

Please try on the latest 3.0.0 beta (beta9 I believe) as the code here has improved a lot since 2.5.3. Code is here for this feature: https://github.com/jekyll/jekyll/blob/9b091f8d5d5800c1332d4653a2928675a2ec7d48/lib/jekyll/frontmatter_defaults.rb#L85-L94

**Comment by iloveip** [comment]
@parkr I tried it with the latest 3.0.0 beta version, but it doesn't work yet.

**Comment by envygeeks** [comment]
@iloveip because #3690 is not merged or finished yet.

**Comment by parkr** [comment]
@iloveip Try v3.0.0.pre.rc1 please! https://github.com/jekyll/jekyll/releases/tag/v3.0.0.pre.rc1

**Comment by iloveip** [comment]
Hello @parkr, thank you very much, but I'm getting some errors when generating the site.

First, I got this error:
````
/Users/svetlana/Desktop/iloveip/_plugins/page_view.rb:2:in `require': cannot load such file -- jekyll/post (LoadError)
````

On line 2 in `page_view.rb` I have:
````
require 'jekyll/post'
````

So I had to remove this line. Then I got another error, which also prevented the site from generating:
````
jekyll 3.0.0.pre.rc1 | Error:  undefined method `strftime' for "2015-09-15":String
````

The date for documents in a collection was set in front matter defaults like this:
````
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "kb"
    values:
      layout: "post"
      date: "2015-09-15"
````

Then, after I removed the date from front matter defaults, I get this error:
````
Deprecation: Collection#sort should be called on the #docs array directly.
             Called by /Users/svetlana/Desktop/iloveip/_plugins/popular_posts.rb:15:in `generate'.
````

On line 15 in `popular_posts.rb` I have:
````
site.collections.each  do |label, collection|
  popular_posts = collection.docs.sort do |px, py|
    if px.data['_pv'] == nil || py.data['_pv'] == nil then 0
      elsif px.data['_pv'] > py.data['_pv'] then -1
      elsif px.data['_pv'] < py.data['_pv'] then 1
      else 0
    end
  end
end
site.config.merge!('popular_posts' => popular_posts) 
````

Although the site is generating now I can't see any of my posts. The posts are called like this:
````
{% assign popular_posts = site.popular_posts %}
{% for node in popular_posts limit:3 %}
    {% include popular_item.html %}
{% endfor %}
````

So I have three questions:
1.  How should I substitute `require 'jekyll/post'` now?
2. Can I still set the date for documents in collections in front matter defaults? And how?
3. How should I change the plugin for popular posts to avoid this deprecation and make the posts display once again?

**Comment by parkr** [comment]
> 1. How should I substitute require 'jekyll/post' now?

This is now `jekyll/document`. It has a slightly different API. It's [the class used for collection documents.](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb)

**Comment by iloveip** [comment]
@parkr thank you very much for your reply.

I will file the bug about the date separately.

I fixed the deprecation. But now I get another error when generating the site:
````
jekyll 3.0.0.pre.rc1 | Error:  undefined local variable or method `popular_posts' for #<Jekyll::PopularPosts:0x007f9eaaef13c0>
````

In my `popular_posts.rb` plugin I have:
````
site.collections.each  do |label, collection|
  popular_posts = collection.docs.sort do |px, py|
    if px.data['_pv'] == nil || py.data['_pv'] == nil then 0
      elsif px.data['_pv'] > py.data['_pv'] then -1
      elsif px.data['_pv'] < py.data['_pv'] then 1
      else 0
    end
  end
end
site.config.merge!('popular_posts' => popular_posts) 
````

How can I fix it?

If I remove this code, the site is generating, but the categories for subdirectories set in front matter defaults as written in my very first message above are still not working. I get a blank space instead.

**Comment by parkr** [comment]
`popular_posts` needs to go outside the `site.collection.each` block. It's out of scope in the `merge!` call.

**Comment by iloveip** [comment]
@parkr If I place `popular_posts` above the block, the site is generating, but I still can't see the posts. Could you please help where is my mistake? I have the following code:
````
popular_posts = site.collections.each  do |label, collection|
  collection.docs.sort do |px, py|
    if px.data['_pv'] == nil || py.data['_pv'] == nil then 0
      elsif px.data['_pv'] > py.data['_pv'] then -1
      elsif px.data['_pv'] < py.data['_pv'] then 1
      else 0
    end
  end
end
site.config.merge!('popular_posts' => popular_posts) 
````

**Comment by envygeeks** [comment]
```ruby
popular_posts = {}
site.collections.each do |label, collection|
  popular_posts.store label, (collection.docs do |px, py|
    _px = px.data.fetch("_pv", 0).to_i
    _py = py.data.fetch("_pv", 0).to_i
    _px > _py ? -1 : _px < _py ? 1 : 0
  end)
end

site.config.store("popular_posts", popular_posts)
```

**Comment by envygeeks** [comment]
The variable name is misleading for what you were doing, there are multiple collections, therefore it needs to be a hash that stores all the collections sorted, if that is not what you want, then you need to adjust popular posts to a set or array and filter until you get the label you want to store (like posts.) but either way, that is a working example.

**Comment by iloveip** [comment]
Hi @envygeeks, thank you very much for your help! I tried to use this code but I got an error:
````
Liquid Exception: no implicit conversion of String into Integer in _includes/popular_posts.html, included in _layouts/post.html
jekyll 3.0.0.pre.rc1 | Error:  no implicit conversion of String into Integer
````

In my `popular_posts.html` I have:
````
{% capture category %}{{ page.category }}{% endcapture %}
{% capture title %}{{ page.title }}{% endcapture %}
{% assign popular_posts = site.popular_posts | where:"category",category %}
{% if page.top %}
  {% for node in popular_posts limit:4 %}
    {% unless node.title == title %}
      {% include popular_item.html %}
    {% endunless %}
  {% endfor %}
{% else %}
  {% for node in popular_posts limit:3 %}
    {% include popular_item.html %}
  {% endfor %}
{% endif %}
````

So far I have only one collection. So I ended up changing the code like this:
````
popular_posts = site.documents.sort do |px, py|
  if px.data['_pv'] == nil || py.data['_pv'] == nil then 0
    elsif px.data['_pv'] > py.data['_pv'] then -1
    elsif px.data['_pv'] < py.data['_pv'] then 1
    else 0
  end
end
site.config.merge!('popular_posts' => popular_posts)
````

I guess when I have more than one collection I will come back to this issue.

**Comment by alvarotrigo** [comment]
So... what's the way to do it then?
[It doesn't seem to work for me](https://github.com/jekyll/jekyll-sitemap/issues/200) when using the following:

```yml
defaults:
  -
    scope:
      path: "assets"
    values:
      sitemap: false 
```

I want it to apply to files with paths like the following:

```
/assets/vanilla-lazyload/demos/with_picture.html
```
