### ISSUE TITLE
no permalinks when loading ajax content into a div

### ISSUE THREAD

**Issue by Muncken87** [jekyll/jekyll#3297]
Hello all

I am pretty new to jekyll and i am doing a portfolio site where you can click on different pictures and you can read more about it , its just that i have no permalinks from my a links or from my thumbnails.

Wherever i go i just stay on the index.html page.

Could anyone help me out with this.

my _config.yml looks like this

```yaml
# Build settings
markdown: kramdown
permalink: pretty
port: 4000
permalink: /:title
include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
```

If you need me to show you some file just say.

Alex
