### ISSUE TITLE
collection permalinks displaying config variables

### ISSUE THREAD

**Issue by yoshyosh** [jekyll/jekyll#3313]
When I add this to my config file:
````yml
collections:
  users:
    output: true
    permalink: '/:collection/:title'
````

My links literally show as localhost:4000/users/:title , rather than taking the title from front matter. Any ideas?
