### ISSUE TITLE
Permalink frontmatter default does not resolve for collections

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jekyll#3334]
I spent some time trying to make a PR for this one, but I'm not sure where the entry point is. The error is either in document.rb or collection.rb.

Say I have a collection like this:

```
_content/
   hidden/
   legacy/
   articles/
```

And my *config.yml* is like this:

``` yaml
collections:
  content:
    output: true
    permalink: articles/:name/index.html
defaults:
  -
    scope:
      path: "legacy"
      type: "content"
    values:
      layout: blank
      exclude_from_search: true
      sitemap: false
      permalink: :name/index.html
```

I would expect that the content in *legacy* would have a permalink of `:name/index.html`. It doesn't; it literally writes a directory called *:name*, with a single file, *index.html*, within it.

![screen shot 2015-01-21 at 12 20 13 am](https://cloud.githubusercontent.com/assets/64050/5833072/5f3b051c-a103-11e4-8be8-5a86fbe3f4c6.png)

**Comment by parkr** [comment]
Weiiiiiird. This is a bug for sure. Good catch. Are you using latest `master`?

**Comment by parkr** [comment]
The problem may have been in `url.rb`, but I think it got fixed?

**Comment by parkr** [comment]
What happens if you add a leading slash?

**Comment by gjtorikian** [comment]
> Are you using latest master?

Yep.

> What happens if you add a leading slash?

I can't believe it, but it looks like appending a forward slash outputs *nothing*.

**Comment by gjtorikian** [comment]
> I can't believe it, but it looks like appending a forward slash outputs nothing.

I'm beginning to think this might be an issue with my `path` definition. Still trying combinations out.

While I have your :ear:, I think a section of the site is wrong: http://jekyllrb.com/docs/configuration/#front-matter-defaults

```
  -
    scope:
      path: ""
      type: "my_collection" # a collection in your site, in plural form
    values:
      layout: "default"
```

` # a collection in your site, in plural form` ? I interpret this to mean, the `value` should be `my_collections`, but that is not the case.

**Comment by gjtorikian** [comment]
Sorry yeah the "nothing output" was an error in my path. Forward slash results in the same problem.

**Comment by gjtorikian** [comment]
Okay, I finally got this working.

First, I was previously using 2.4.0. SORRY!

Second, it seems like you must set a default permalink on the collection first. Then, your defaults `path` will derive off of that. For example:

``` yaml
collections:
  content:
    output: true
    permalink: /:path/index.html
defaults:
  -
    scope:
      path: "legacy"
      type: "content"
    values:
      layout: blank
      exclude_from_search: true
      sitemap: false
      permalink: :name/index.html
```

`permalink: /:path/index.html` is key! That's picked up by `path` to determine the scope. I guess it makes sense if you think about it a bit harder, but I assumed `path` referred to the prerendered endpoint.

I think we can close this out, unless you see something off about this.
