### ISSUE TITLE
Subproperties in YAML

### ISSUE THREAD

**Issue by ricardopolo** [jekyll/jekyll#3357]
I have this markup in the Front Matter

````yaml
title:  "Some Title"
subcategories:
  a:
    id: a
    text: "Text 1"
  b:
    id: b
    text: "Text 2"
```

I use it this way
````html
<ul id="sidebar" class="nav nav-stacked">
{% for item in site.portfolio_content %}
<li>
  <a href="#{{ item.title }}">{{ item.title }}</a>
  <ul class="nav nav-stacked">
    {% for subcategorie in item.subcategories %}
    <li><a href="#{{ subcategorie.id }}">{{ subcategorie.text }}</a></li>
    {% endfor %}
  </ul>
</li>
````

``{{ subcategorie.id }}`` and ``{{ subcategorie.text }}`` translates to empty.
Why I can't access to ``id`` and ``text``?

If I access to ``{{subcategorie}}`` after Jelkyll it gets translated to ``{"id"=>"a",, "text"=>"Text 1"}`` but when I access ``{{subcategorie.id}} or ``{{subcategorie.text}} it gets empty. What am I doing wrong?

**Comment by parkr** [comment]
Iterating over a hash is not quite so simple. I believe it's generally turned into an array, where the first item is the key, and the second is the value. Try `subcategorie[1].id`. Side note: it's generally `subcategory` with a `y` but that's beside the point. :wink:

**Comment by nickhammond** [comment]
I think what you're looking for is:

```
subcategories:
  - id: a
    text: "Text 1"
  - id: b
    text: "Text 2"
```

This will give you an array of categories that will work with your loop, more specifically with `{{ subcategory.id }}` and `{{subcategory.text}}`.
