### ISSUE TITLE
Bug: Collections don't work with incremental regeneration

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll#3367]
`_config.yml`:
```
collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  -
    scope:
      path: ''
    values:
      layout: default
```
Now after running `jekyll s`, if I change something in `_layouts/default.htm`, the output of the files in the docs collection won't update.
