### ISSUE TITLE
Jekyll: Printing Nested Front Matter

### ISSUE THREAD

**Issue by realph** [jekyll/jekyll#3564]
I'm trying to print my front matter to the page, but I'm having a problem printing this nested data to the page.

**.md file**

    gallery:
       row:
          image: { url: 'img.jpg', ratio: '1.7486338798' }
          image: { url: 'img.jpg', ratio: '1.7486338798' }

**post.html**

    {% for img in page.gallery.row.image %}
      <img src="{{ img.url }}" alt="" data-aspect-ratio="{{ img.ratio }}" />
    {% endfor %}

Nothing's showing up in my HTML output. Am I doing something wrong here? Am I nesting Front Matter in YAML correctly?

Any help is appreciated. Thanks in advance!

**Comment by parkr** [comment]
Yeah, the YAML is improperly written. You have defined a hash with one key that is redefined. Try this:

```yaml
gallery:
   row:
      image:
        - { url: 'img.jpg', ratio: '1.7486338798' }
        - { url: 'img.jpg', ratio: '1.7486338798' }
```
