### ISSUE TITLE
How do I remove line numbers when using Coderay

### ISSUE THREAD

**Issue by Nerian** [jekyll/jekyll#359]
How do I remove line numbers when using Coderay

```
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
```

I tried changing coderay_line_numbers to nil, but it gives me the following error

```
..../html/numerization.rb:110:in `numerize!': Unknown value :nil for mode: expected one of [:table, :list, :inline] (ArgumentError)
```

¿So, how do I remove line numbers when using Coderay?

**Comment by vermiculus** [comment]
I'm also having this issue, it seems.  I've tried
```yaml
kramdown:
  use_coderay: false
  coderay_line_numbers: nil
```
and
```yaml
kramdown:
  use_coderay: false
  coderay:
    coderay_line_numbers: nil
```
but neither works.

Related:
- http://blog.codebykat.com/2013/05/23/gorgeous-octopress-codeblocks-with-coderay/
- http://kramdown.gettalong.org/options.html

**Comment by parkr** [comment]
> Turns out the fix was to stop and restart the Jekyll server.

Your `_config.yml` is not re-read in the `--watch` loop.

**Comment by mFingers** [comment]
I got this to work by **not** separating out and indenting the coderay configuration:

``` yaml
kramdown:
  input: GFM
  enable_coderay: true
  coderay_line_numbers: inline
  coderay_css: class
```
 I figured this would work because these options are first-class [options to kramdown](http://kramdown.gettalong.org/options.html).

jekyll: 2.5.3
kramdown: 1.8.0
coderay: 1.1.0
