### ISSUE TITLE
Rouge syntax highlighting problem

### ISSUE THREAD

**Issue by MarcoDeBortoli** [jekyll/jekyll#3641]
Hi there, I'm posting here after raising this issue with the rouge lead developer and realising that it's more likely to be an issue with jekyll itself. 

The issue is that jekyll doesn't highlight properly my code when I use rouge in the following scenario.

1. I create the `syntax.css` file as:

    ```bash
    $ bundle exec rougify style base16.solarized.dark > css/syntax.css
    ```

2. I configure jekyll as:

    ```yaml
    # Build settings
    markdown: kramdown
    highlighter: rouge
    ```

3. I create a post as:

    ```markdown
    ---
    layout: post
    title: Hello World
    ---
    ### Hello world

    {% highlight php %}
    <?php

    echo 'Hello world!';

    {% endhighlight %}
    ```

However, if I do change the `_config.yml` to be like this:

```yaml
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
```

And the post to be like:

```markdown
    ---
    layout: post
    title: Hello World
    ---
    ### Hello world

    ```php
    <?php

    echo 'Hello world!';
    ```
```
Everything works as expected. Anyone who is able to shed some light on this? Am I overlooking something or is there actually a bug?
