### ISSUE TITLE
Jekyll Defaults has quirky matching that leads to confusing implementations.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3730]
Take for example me trying to target a specific path as a user I would try:

```yaml
defaults:
  - scope:
      path: "blog.html"
      type: "pages"
    values:
      layout: "default"
```

However, the implementation of Jekyll defaults is pretty quirky and [`sanitize_path`](https://github.com/jekyll/jekyll/blob/091e86aa22d3987ada1388428ea81263ba62f7a3/lib/jekyll/frontmatter_defaults.rb#L89) adds a forward slash to the end (btw that's not sanitizing that's normalizing at that point.)  Which means you end up targeting quirky behavior to target a specific page:

```yaml
defaults:
  - scope:
      path: "blog.html/"
      type: "pages"
    values:
      layout: "default"
```

I have tested and confirmed this is the behavior on the current beta through Jekyll Docker.
