### ISSUE TITLE
Can't make my collection output

### ISSUE THREAD

**Issue by aug-riedinger** [jekyll/jekyll#3754]
I have this collection:

```
# _config.yml
collections:
  resources:
    output: true
    permalink: /resources/:title/
```

And the folder `_resources` containing `my-post.md`, looking like

```
---
layout: post
title:  My post title
date: 2014-09-09
tags: tech
lang: en
images:
  thumb: database_postgres.png
  medium: database_postgres.png
---
 
My markdown content
```

When I use:

```
{% for resource in site.resources %}
  {{ resource.title }}
{% endfor %}
```
it works, but in the `_site/resources/`, `my-post.html` or `my-post/index.html` are not there.

Also also probably should mention that I have a `resources.html` page, looking like so:

```
---
layout: default
title: Resources
permalink: /resources/
---

<!-- html content -->
```
generating `_site/resources/index.html` but even if I change to `permalink: /resources2/` it doesn't work so I guess it is not interfering.

Been doing some searches, reading the docs many time, also [external resources](http://www.sitepoint.com/getting-started-jekyll-collections/) and finally tried to debug the `~/.rvm/gems/ruby-2.1.4/gems/jekyll-2.5.3` content, without success.

Thanks for support
