### ISSUE TITLE
Unclear Collections doc: feedbacks from a newcomer

### ISSUE THREAD

**Issue by aug-riedinger** [jekyll/jekyll#3755]
In the following file: https://github.com/jekyll/jekyll/blob/master/site/_docs/collections.md

when writing: `Default attributes can also be set for a collection:`

```
defaults:
  - scope:
      path: ""
      type: my_collection
    values:
      layout: page
```
it would be clearer to have:
```
collections:
  my_collection:
    defaults:
      - scope:
          path: ""
          type: my_collection
        values:
          layout: page
```
or maybe that's me who's wrong (as I did not get it).

Also, it is mentioned how to access collection content in other pages:
```
{% for album in site.albums %}
  <h2>{{ album.title }}</h2>
  <p>Performed by {{ album.artist }}{% if album.director %}, directed by {{ album.director }}{% endif %}</p>
  {% for work in album.works %}
    <h3>{{ work.title }}</h3>
    <p>Composed by {{ work.composer }}</p>
    <ul>
    {% for track in work.tracks %}
      <li>{{ track.title }} ({{ track.duration }})</li>
    {% endfor %}
    </ul>
  {% endfor %}
{% endfor %}
```

But I haven't found anywhere how to access data *within* the file, when `output: true` is set:

```
---
layout: album
title: "Josquin: Missa De beata virgine and Missa Ave maris stella"
artist: "The Tallis Scholars"
director: "Peter Phillips"
works:
  - title: "Missa De beata virgine"
    composer: "Josquin des Prez"
    tracks:
      - title: "Kyrie"
        duration: "4:25"
      - title: "Gloria"
        duration: "9:53"
      - title: "Credo"
        duration: "9:09"
      - title: "Sanctus & Benedictus"
        duration: "7:47"
      - title: "Agnus Dei I, II & III"
        duration: "6:49"
---

<!-- How do I access title?? -->
<h1>{{page.title}}</h1>
<!-- Or -->
<h1>{{self.title}}</h1>
```

And in `_layouts/album.html`:

```
---
layout: default
---
<!-- How do I access title?? -->
<h1>{{page.title}}</h1>
<!-- Or -->
<h1>{{self.title}}</h1>
```

Thanks for consideration
