### ISSUE TITLE
Default collection permalink overrides collection permalink

### ISSUE THREAD

**Issue by larryfox** [jekyll/jekyll#3819]
Not sure if this is a bug or expected behavior, and it seems like a very unusual case but:

```yaml
defaults:
  - scope:
      path: ""
      type: colors
    values:
      permalink: /not_colors/:path/ # this overrides collection settings (order does not matter)

collections:
  colors:
    output: true
    permalink: /my_colors/:path/
```

I would expect the permalink defined in the actual collection definition to take precedence over a default (which to me implies "value to fallback to if not set").

But if you render that out you end up with documents in the `/not_colors/` folder, not `/my_colors`

![](http://fox.dropmark.com/225177/5013771.png)

This is on `3.0.0.pre.beta7`
