### ISSUE TITLE
iframes not being rendered correctly

### ISSUE THREAD

**Issue by damienh** [jekyll/jekyll#3822]
In our Jekyll site we have iframes appearing like this:

![screen shot 2015-06-24 at 15 02 09](https://cloud.githubusercontent.com/assets/810107/8357342/621baaec-1b52-11e5-8a8a-0c3fad82154f.png)

Here is our config file where we use pandoc to convert markdown to html

```
gems: [ 'jekyll-pandoc-multiple-formats' ]
pandoc:
  output: ./tmp
  flags: '--parse-raw --smart --section-divs'
  outputs:
    markdown: redcarpet
```

I tried setting kramdown and redcarpet but it doesnt seem to help.

here is the iframe in our markdown file

```
<div class="scratch-preview">
	<iframe allowtransparency="true" width="485" height="402" src="http://scratch.mit.edu/projects/embed/26818098/?autostart=false" frameborder="0"></iframe>
	<img src="space-final.png">
</div>
```

If anyone can point me in the right direction it would be very much appreciated.
