### ISSUE TITLE
Collections not outputting as .html

### ISSUE THREAD

**Issue by dvichris** [jekyll/jekyll#3869]
I've tried several different attempts and for some reason every time the site is built it keeps the md format  even using `output_ext: .html` does not work.

My _config.yml:

```
# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  cupcakes:
    output: true
    permalink: /cupcakes/:path/
```

After trying jekyll build in terminal it builds the site correctly but in the cupcakes folder the same .md file is still there and no .html file.

Any assistance would be greatly appreciated.
