### ISSUE TITLE
Collection markdown files not being processed and collections array empty

### ISSUE THREAD

**Issue by underhilllabs** [jekyll/jekyll#3898]
Hi, I'm working on a jekyll 2.5.3 site with Book Reviews and Cheatsheet collections and the collections are not being populated and the files in the collections are being moved over without being processed.

Here's the code:
https://github.com/underhilllabs/mu-blog

My _config.yml has:

```yaml
collections:
  cheatsheets:
    output: true
    output_ext: .html
    permalink: /cheatsheets/:path/
  book_reviews:
    output: true
    output_ext: .html
    permalink: /bookreviews/:path/
```

and the _book_reviews/ubik.md has a front matter of:

```yaml
--- 
layout: page
title: Book Review Ubik by Philip K. Dick
category: scifi
tags: [scifi, pkd]
---
```

but ubik.md is copied over unprocessed and when I try loop through site.book_reviews the array is empty.

I apologize if I am doing something wrong, but I've read the docs and looked for other collection sites and every on my site appears to be correct.

Thanks!
