### ISSUE TITLE
Jekyll beta Unknown tag 'gist'

### ISSUE THREAD

**Issue by sparanoid** [jekyll/jekyll#3906]
After searching for a while I still can't resolve it. I just updated jekyll to pre.beta8,  and got the following error when compiling my site:

```sh
$ bundle exec jekyll build --config _config.yml,_amsf/_config.yml,_app/_data/curtana.yml,_config.dev.yml --drafts --trace

Configuration file: _config.yml
Configuration file: _amsf/_config.yml
Configuration file: _app/_data/curtana.yml
Configuration file: _config.dev.yml
            Source: _app
       Destination: _site
 Incremental build: enabled
      Generating... 
/usr/local/lib/ruby/gems/2.2.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: already initialized constant Rouge::Lexers::Shell::KEYWORDS
/usr/local/lib/ruby/gems/2.2.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: previous definition of KEYWORDS was here
/usr/local/lib/ruby/gems/2.2.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: already initialized constant Rouge::Lexers::Shell::BUILTINS
/usr/local/lib/ruby/gems/2.2.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: previous definition of BUILTINS was here
  Liquid Exception: Liquid syntax error: Unknown tag 'gist' in _drafts/2014-06-11-markup-example.md
/usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:87:in `unknown_tag': Liquid syntax error: Unknown tag 'gist' (Liquid::SyntaxError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:38:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/tag.rb:10:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/document.rb:5:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:122:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:108:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/liquid_renderer/file.rb:11:in `block in parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/liquid_renderer/file.rb:10:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/convertible.rb:246:in `do_layout'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/post.rb:273:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:180:in `block in render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:178:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:178:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/site.rb:59:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:35:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta8/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

In `_drafts/2014-06-11-markup-example.md`:

```md
{% gist sparanoid/55c3dd64f94881017a7b gist.md %}

{% gist sparanoid/87b4b3ec181e90146c74 %}
```

Main config snippet:

```yaml
#
# Jekyll basic configurations
#

source:         _app
destination:    _site
timezone:       Asia/Hong_Kong
permalink:      /:categories/:title/
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]

#
# Additional Markdown settings
#

kramdown:
  input:              GFM
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  enable_coderay:     true
  syntax_highlighter: rouge
```

Other configs only provide some custom variables.
