### ISSUE TITLE
Where filter always treats value as a string 

### ISSUE THREAD

**Issue by omgmog** [jekyll/jekyll#3911]
I noticed recently that the `where:` filter treats the value option as a string, even if a boolean is used:

Example post frontmatter:
``` yaml
---
title: foo
featured: true
---
```

Example usage of `where:` filter:

``` liquid
{% assign featured_posts = ( site.posts | where: "featured", true ) %}

>> featured_posts is empty
```

The same result is seen if we wrap `true` in quotes on the `where:` filter:

``` liquid
{% assign featured_posts = ( site.posts | where: "featured", "true" ) %}

>> featured_posts is empty
```

To make this work I had to wrap the `true` in quotes in both cases:

``` yaml
---
title: foo
featured: "true"
---
```

``` liquid
{% assign featured_posts = ( site.posts | where: "featured", "true" ) %}

>> featured_posts contains foo
```
