### ISSUE TITLE
Implicit .file excludes are not taken into account by --watch

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll#3912]
The [doc](http://jekyllrb.com/docs/configuration/#global-configuration) says "dotfiles are excluded by default". Which is correct and working, nothing starting with `.` appears in `_site` unless I put it in `site.include`.

In Jekyll 2.4.0 (because of [gh-pages](https://github.com/github/pages-gem)) regeneration is triggered by anything that's starting with a `.`:
(file names come from [this hack](http://www.twisterrob.net/blog/2015/06/Jekyll-hacks-for-development.html#continous-development))
```yaml
# Saved _06_typography.scss
           Changes: Modified _sass/_06_typography.scss
      Regenerating: 1 file changed at 2015-08-13 12:40:13 ...done in 4.268843 seconds.
           Changes: Modified .sass-cache/95b8d59b2262bcc9b16d60cd1aead129197e78ea/_06_typography.scssc
      Regenerating: 1 file changed at 2015-08-13 12:40:17 ...done in 4.28283 seconds.
# Created .hello folder and touched world.txt file
           Changes: Added .hello/world.txt
      Regenerating: 1 file changed at 2015-08-13 12:50:03 ...done in 4.25304 seconds.
# Edited .gitignore file
           Changes: Modified .gitignore
      Regenerating: 1 file changed at 2015-08-13 12:52:14 ...done in 4.286231 seconds.
```

As a workaround I modified my `_config.yml` and the extra regenerations stopped:
```yml
exclude:
  - .gitignore
  - .sass-cache
```
`.hello/world` still triggers, because I not included that (I don't really create random directories), but it would be nice if the implicits work the same across the system.
