### ISSUE TITLE
site.exclude and serve regeneration are highly inconsistent

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll#3913]
I'm using Jekyll 2.4.0 because of [gh-pages](https://github.com/github/pages-gem) :(

Suppose the following directory and file structure:
```yaml
root:
 - .git
 - .other
     - test
 - assets
     - build.gradle
     - something.bat
 - .gitignore
 - _config.yml
 - _config_dev.yml
 - build.gradle
 - clean.bat
```

## Default
By default (empty configs, `jekyll build`) the `_site` generated looks like this:
```yaml
 - assets
     - build.gradle
     - something.bat
 - build.gradle
 - clean.bat
```
That is the dotfiles are implicitly excluded as the [doc](http://jekyllrb.com/docs/configuration/#global-configuration) says. Regeneration is triggered by touching most files, except `.git` folder contents and `_config.yml`:
```yaml
           Changes: Modified .other/test
      Regenerating: 1 file changed at 2015-08-13 13:22:15 ...done in 0.004 seconds.
           Changes: Modified assets/build.gradle
      Regenerating: 1 file changed at 2015-08-13 13:17:56 ...done in 0.007 seconds.
           Changes: Modified assets/something.bat
      Regenerating: 1 file changed at 2015-08-13 13:17:58 ...done in 0.008001 seconds.
           Changes: Modified .gitignore
      Regenerating: 1 file changed at 2015-08-13 13:17:43 ...done in 0.004 seconds.
           Changes: Modified _config_dev.yml
      Regenerating: 1 file changed at 2015-08-13 13:19:47 ...done in 0.0 seconds.
           Changes: Modified build.gradle
      Regenerating: 1 file changed at 2015-08-13 13:17:50 ...done in 0.008 seconds.
           Changes: Modified clean.bat
      Regenerating: 1 file changed at 2015-08-13 13:17:52 ...done in 0.007 seconds.
```

## Enter exclude
I modified `_config.yml` to have the following contents:
```yaml
exclude:
  - build.gradle
  - .git
  - '*.bat' # needs quotes because of the star
```

Generated site after another serve:
```yaml
 - assets
     - build.gradle
```

After touching every file:
```yaml
           Changes: Modified .other/test
      Regenerating: 1 file changed at 2015-08-13 13:24:31 ...done in 0.003 seconds.
           Changes: Modified assets/something.bat
      Regenerating: 1 file changed at 2015-08-13 13:24:24 ...done in 0.006001 seconds.
           Changes: Modified _config_dev.yml
      Regenerating: 1 file changed at 2015-08-13 13:24:13 ...done in 0.003001 seconds.
           Changes: Modified clean.bat
      Regenerating: 1 file changed at 2015-08-13 13:24:18 ...done in 0.003 seconds.
```

## Issues

 * `.other/test` triggers regeneration even though it's implicitly excluded
 * `assets/build.gradle` doesn't trigger regeneration even though it's copied to `_site`  
  (impossible to modify the file, I have to restart `jekyll serve)
 * Any bat file triggers regeneration even thought they're explicitly excluded
 * `_config.yml` doesn't trigger regeneration, but `_config_dev.yml` does  
   (even with `--config _config.yml,_config_dev.yml`)
 * `.git` in the exclude list excludes `.gitignore`, so `x` means `x*`?!  
   This is known because `.gitignore` doesn't trigger regeneration after excluding `.git`.
 * `.gitignore` triggers regeneration without the excludes (#3912)
 * one of these seems wrong, either way they are inconsistent:
   * `*.bat` excludes the one in the subfolder
   * `build.gradle` doesn't exclude the one in subfolder
