### ISSUE TITLE
Issue with non-standard Frontmatter defaults for sub-directories within posts

### ISSUE THREAD

**Issue by rocketspops** [jekyll/jekyll#3928]
In the following example from my project's `_config.yml` file, `marketing` represents a sub-directory within `_posts`: 

```
- scope:
    path: marketing
  values:
    author: "John Smith"
    category: marketing
```

 When setting Frontmatter defaults for this path inside of my `_config.yml` I am able to set values for `category`, `layout` and `tags` as expected. 

However, when I try to set a value for `author` or some other non-standard key (like `og_profile` or `sub-heading`), I am unable to access the value from within the page template using a liquid tag, as it simply returns a null value.

However, if I set the value in the Frontmatter of the actual post itself, I'm able to access the value as expected (e.g. `{{ page.author }}` correctly resolves the value I supplied to the `author` key).

**Comment by envygeeks** [comment]
Hey @rocketspops can you please provide a replicate-able example or at least more context on the source, it's really hard to get a full grasp without working examples or stronger context.  Thanks!

**Comment by rocketspops** [comment]
```
defaults:
- scope:
    path: ""
  values:
    layout: default
- scope:
    path: ""
    type: drafts
  values:
    layout: post
    type: draft
    tags: drafts
- scope:
    path: ""
    type: posts
  values:
    layout: post
    type: post
    tags: uncategorized
- scope:
    path: joshua-davison
  values:
    author: "John Smith"
    og_profile: "https://www.facebook.com/john-smith"
    category: john-smth
- scope:
    path: marketing
  values:
    category: marketing
```

Hey @envygeeks, thanks for the quick response. In the example above from my `_config.yml` I'm able to access the `category` value for all posts in `_posts/john-smith` but not the `author` or `og_profile` values.
