### ISSUE TITLE
Can dates be included in collection permalinks?

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#3942]
I’m using Jekyll 3.0.0.pre.beta8. My site has three kinds of pages: the usual pages and posts and also link posts, which are essentially the same as “normal” posts except that they use a different layout and have different permalinks.

I would like to implement link posts as a collection but it seems that I can’t use dates in collection permalinks: with the configuration below, the links are all written to paths like

    /links/:year/:month/2015-08-28-whatever.html

while I was expecting paths like

    /links/2015/08/whatever.html

Is there something wrong with my configuration or are these parameters not (yet?) supported for collection permalinks?

The relevant parts of my configuration are as follows:

```
permalink: :year/:month/:title.html
collections:
    links:
        output: true
        permalink: links/:year/:month/:title.html
defaults:
    - scope:
        path: ""
        type: pages
      values:
        layout: new

    - scope:
        path: ""
        type: posts
      values:
        layout: article

    - scope:
        path: links
        type: links
      values:
        layout: link
```

The input files have paths like

    _links/2015-08-28-whatever.md
