### ISSUE TITLE
What are the working Jekyll permalinks in GitHub Pages?

### ISSUE THREAD

**Issue by 5ervant** [jekyll/jekyll#4037]
Can I know the list of the working permalinks in GitHub Pages for a Jekyll-powered page?
One of I believed that's working is: `permalink: /:title/`
http://stackoverflow.com/q/33175753/4883372

And also the other working permalinks than `permalink: /:categories/:year/:month/:day/:title` for a blog post? Because `permalink: /:path/:basename/` is working in my local but not in GitHub Pages.

I believe that all of the listed permalinks in this area http://jekyllrb.com/docs/permalinks/#pages-and-collections will not work in GitHub Pages, am I true? *(Thanks for any responds..)*

**Comment by akhyarrh** [comment]
```yaml
permalink: /post/:title
# rendered to sometime /post/title.html
permalink: /post/:title/
# rendered to /post/title/index.html
```

Use option 1 if want to experimenting and take a litle risk (?).
Use option 2 to make it sweet.
