### ISSUE TITLE
Problem rendering text between two horizontal rules using markdown

### ISSUE THREAD

**Issue by julianofischer** [jekyll/jekyll#4044]
I am using Jekyll 2.5.3

The following should render the text with two horizontal rules, one above and another below the text.
    ---
    Text
    ---
    ***
    Text
    ***

However, the result is:

    ---horizontalruleok
    Text---

    ***horizontalruleok
    Text***

That is, only the horizontal rule above the text is rendered and the text is succeeded by  --- (or ***, both cases lead to the same behavior).

**Comment by envygeeks** [comment]
Without seeing a sreenshot or the html result I'm going to flatly say this is either a bug in your markdown processor (as it's the one that does this) or your CSS (if they are both printed but there are display errors.)

**Comment by i-give-up** [comment]
Can reproduce this with the default markdown processor Kramdown. 

Given that markdown's specification is a bit ambiguous, you can't really say this is the expected behavior or not. Perhaps with Kramdown you need a blank line before `---` or `***` will be interpreted as a horizontal rule.

In any case, [Kramdown's syntax documentation](http://kramdown.gettalong.org/syntax.html#horizontal-rules) doesn't specify the expected behavior when you have text in between two `---` (or `***`) lines.

**Comment by julianofischer** [comment]
Hi, I would like to thank you for your attention.
I apologize for the lack of information.
I describe the details below in order to provide arguments for further discussion.

I use remarkable as markdown editor: ![remarkable](https://cloud.githubusercontent.com/assets/158303/10564355/b4bdedfe-758f-11e5-8224-854fa6e6d030.png)

Jekyll output:
![captura_de_tela-3](https://cloud.githubusercontent.com/assets/158303/10564371/5b6e1c64-7590-11e5-9c01-95c5f81ff95d.png)

Jekyll HTML outpt:

``` html
    <p>Text
    —</p>

    <hr />
    <p>Text
    ***</p>
```
The theme I use: https://github.com/KingFelix/emerald

hr tag css rules:

``` css
element {
}
* {
    box-sizing: border-box;
}
body {
    font-family: "Source Sans Pro",sans-serif;
    letter-spacing: 0.01em;
}
html {
    font-size: 18px;
}
html {
    font-size: 16px;
    line-height: 1.5;
    color: #222;
}
```
p tag css rules:

``` css

element {
}
p, ul, ol {
    font-size: 1em;
    line-height: 1.3334em;
    margin-bottom: 1.3334em;
}
p, ul, ol {
    font-size: 1em;
    line-height: 1.5em;
    margin-bottom: 1.5em;
}
html, body, h1, h2, h3, h4, h5, h6, p, ul, ol, li, img {
    margin: 0px;
    padding: 0px;
    border: 0px none;
}
* {
    box-sizing: border-box;
}
body {
    font-family: "Source Sans Pro",sans-serif;
    letter-spacing: 0.01em;
}
html {
    font-size: 18px;
}
html {
    font-size: 16px;
    line-height: 1.5;
    color: #222;
}
```
