### ISSUE TITLE
Post defaults not recognised in Jekyll v3.0.0

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#4064]
Given the following provided in config.yml:

```yaml
defaults:
  - scope:
      type: posts
      path: '_posts'
    values:
      layout: entry
      type: entry
      license:
        type: Creative Commons
        url: http://creativecommons.org/licenses/by-nc-sa/4.0/
```

and the following liquid markup:

```html
<pre>Type: {{ page.type }}</pre>
<footer>
{% if page.license %}
    <a rel="license" href="{{ page.license.url }}">{{ page.license.type }}</a>
{% endif %}
</footer>
```

the following is (not) generated:

```html
<pre>Type: </pre>
<footer>
</footer>
```

This was working in versions prior to rc1.

**Comment by parkr** [comment]
What happens if you set `path: ""`?

**Comment by paulrobertlloyd** [comment]
That does work – but of course, my setup requires me to declare different paths:

```yaml
defaults:
  - scope:
      type: content
    values:
      layout: content
      type: content

  - scope:
      type: posts
      path: '_posts/entries'
    values:
      layout: entry
      type: entry
      license:
        type: Creative Commons
        terms: BY-NC-SA
        description: 'You can republish this content without asking permission, but you must credit me (Paul Robert Lloyd) as the author and provide a link back to the original. You may not use any content for commercial purposes. If you make any changes, you must distribute these under the same license as the original.'
        url: http://creativecommons.org/licenses/by-nc-sa/4.0/

  - scope:
      type: posts
      path: '_posts/links'
    values:
      layout: entry
      type: link

  - scope:
      type: posts
      path: '_posts/galleries'
    values:
      layout: gallery
      type: gallery
      theme: dark

  - scope:
      type: projects
    values:
      layout: project
      type: project

  - scope:
      type: talks
    values:
      layout: talk
      type: talk

  - scope:
      type: discussions
    values:
      layout: discussion
      type: discussion
```
