### ISSUE TITLE
Date for collections in front matter defaults is not working

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#4068]
Hello,

I upgraded to v3.0.0.pre.rc1. In my front matter defaults I have a date set for documents in a collection like this:

````
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "kb"
    values:
      layout: "post"
      date: "2015-09-15"
````

But it's not working. When I generate the site I get the following error:
````
jekyll 3.0.0.pre.rc1 | Error:  undefined method `strftime' for "2015-09-15":String
````
