### ISSUE TITLE
defaults configuration seems ignore type: "drafts"

### ISSUE THREAD

**Issue by simba4everyoung** [jekyll/jekyll#4080]
I encountered a problem same with #2726 in jekyll 3.0.0
I want to set default author for drafts. In my _config.yml I have:

```
defaults:
    -
        scope:
            path: "" 
            type: "drafts" 
        values:
            author: Simba Draft
            layout: "post"

    -
        scope:
            path: "" 
            type: "posts" 
        values:
            layout: "post"
```

I tried this, also tried setting posts before drafts. I can't get drafts' author set. All the posts are without author now. 
Any ideas? :smiley:
