### ISSUE TITLE
Access default values in a hook, debugging

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4155]
My config has `defaults` that look like:
```
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
      show_breadcrumb: true
      show_disqus: true
      print_pdf: true
```

I wrote a hook that looks like:
```
Jekyll::Hooks.register :pages, :post_write do |page|
```

Using the debug tool, printing `page.data` shows a json object of all the page's metadata but NOT the ones from the config file.

But printing `page.data["print_pdf"]` directly does print the correct value (`true`).
