### ISSUE TITLE
:title permalink variable not working with custom collections

### ISSUE THREAD

**Issue by mshick** [jekyll/jekyll#4172]
I have a custom collection type `members` with files named `1-jane-doe.md`, `2-tim-smith.md`, each with a title, like `title: Jane Doe`, `title: Tim Smith`. 

I set my custom collection permalink to `/team/:title` in both defaults and the collections hash (and each individually in the course of testing). The generated site always ends up with paths like `team/1-jane-doe` and not `team/jane-doe` as though it didn't see the title at all. 

Setting the permalink explicitly in the frontmatter _does_ work, and the config-set permalink pattern is utilized, as I can manipulate the path with it.

Some snippets:

> `_config.yml`

```yaml
# Outputting
permalink: pretty

# Collections
collections:
  members:
    output: true
    permalink: /team/:title/

# Front-matter defaults
defaults:
  -
    scope:
      path: ""
      type: "members"
    values:
      layout: "page"
      permalink: /team/:title/
```

> `1-jane-doe.md`

```md
---
title: Jane Doe
---
Foo
```

> `2-tim-smith.md`

```md
---
title: Tim Smith
---
Bar
```

Generated files/paths:

`team/1-jane-doe/index.html`  
`team/2-tim-smith/index.html`

**Comment by rebornix** [comment]
If I remember correctly, Jekyll will just use the `:title` fragment in the file name to generate permalinks. It makes sense to me as I may want to use Chinese (whatever language you like) to name my title in front matter and it would be ugly if Jekyll take it as permalinks.

Let's say we have a post called `2011-10-19-hippolytus.md` with content

```
---
title: 希波吕托斯
---
Hippolytus (Ancient Greek: Ἱππόλυτος, Hippolytos) is an Ancient Greek tragedy by Euripides, based on the myth of Hippolytus, son of Theseus. The play was first produced for the City Dionysia of Athens in 428 BC and won first prize as part of a trilogy.
```

For now, Jekyll will generate `/2011/10/19/hippolytos/` for me, which is pretty. However, if Jekyll consumes the title from FM, the url will be like `/2011/10/19/%E5%B8%8C%E6%B3%A2%E5%90%95%E6%89%98%E6%96%AF/`. I suppose you can get my idea, the url encoding is really annoying here.

**Comment by mshick** [comment]
@rebornix I see what you're saying, but that's not how `:title` is described in the [docs](http://jekyllrb.com/docs/collections/):

> The document's lowercase title (as defined in its front matter), with every sequence of spaces and non-alphanumeric characters replaced by a hyphen. If the document does not define a title in its front matter, this is equivalent to name.

You also present a valid case, and the way I've seen other systems handle this sort of thing is to use a special `slug` or `handle` variable, which would be a slugified title, but could also be set directly. For your example, you might end up with frontmatter like this:

```yaml
---
title: 希波吕托斯
handle: hippolytos
---
```

I'd also favor a new variable rather than overloading `:name` or the current `:title` because all three have unique cases and uses.
