### ISSUE TITLE
jekyll serve --watch is not watching for sass changes

### ISSUE THREAD

**Issue by joannaho** [jekyll/jekyll#4212]
I just downloaded Jekyll sample to test out the "jekyll serve --watch" function on sass compiling, but it is not working for me. "jekyll serve" doesn't watch anything to poll for change. Is anyone having the same issue?

I have jekyll 3.0.1, Python 2.7.5, Node 0.10.32, Sass 3.4.19, Compass 0.12.2 installed. 

My "_config.yml" setting: 

```yaml
# General settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
```
