### ISSUE TITLE
Defaults: Path scope with subfolders

### ISSUE THREAD

**Issue by CGarces** [jekyll/jekyll#4331]
Check the following site at github

http://cgarces.github.io/jekyllrb_multilanguage/
the source is at https://github.com/CGarces/jekyllrb_multilanguage

The post language is showed between the "-" chars and assigned by _config.yml

The folder structure is 

```
_posts
 es
   0000-01-01-sample.md
 en
   0000-01-01-sample.md
```

And my config file contains...

```
defaults:
  -
    scope:
      path: "_posts/es"
    values:
      layout: default
      lang: es
  -
    scope:
      path: "_posts/en"
    values:
      layout: default
      lang: en
```

But fails on my development environment 
$ jekyll -v
jekyll 3.0.1

It's a specific bug of 3.x?

**Comment by parkr** [comment]
I believe 3.0.x has this bug but not 3.1.x. If you're able to try the beta, please do!

**Comment by CGarces** [comment]
I can't test it.
```
Fetching: jekyll-3.1.0.pre.beta1.gem (100%)
Successfully installed jekyll-3.1.0.pre.beta1
Parsing documentation for jekyll-3.1.0.pre.beta1
Installing ri documentation for jekyll-3.1.0.pre.beta1
Done installing documentation for jekyll after 3 seconds
1 gem installed
```

```
$ jekyll serve -w
/var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/drops/document_drop.rb:5:in `<module:Drops>': uninitialized constant Jekyll::Drops::Drop (NameError)
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/drops/document_drop.rb:4:in `<module:Jekyll>'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/drops/document_drop.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll.rb:11:in `block in require_all'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll.rb:10:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll.rb:10:in `require_all'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/lib/jekyll.rb:175:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/jekyll-3.1.0.pre.beta1/bin/jekyll:6:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
@CGarces Thanks for letting me know! Let me release another beta now.

**Comment by parkr** [comment]
We'll have to wait until #4328 is merged. Once that's done, I'll release!

**Comment by moabi** [comment]
Same here, layout product will be applied on sub folder "modules"

    -
    scope:
      path: "fr-FR"
    values:
      i18n: "fr-FR"
      layout: "product"
    -
    scope:
      path: "fr-FR/modules"
    values:
      i18n: "fr-FR"
      layout: "modules"

**Comment by envygeeks** [comment]
#4328 is resolved and the tests are passing again.  /cc @parkr

**Comment by CGarces** [comment]
I have moved my structure to use collections

Now I have:

```YAML
collections:
  docs:
    output: true
    permalink: "/:title"
    lang: "default"

defaults:
  -
    scope:
      type: "docs"       
      path: "/es/"
    values:
      layout: default
      lang: "es"
  -
    scope:
      type: "docs"     
      path: "/en/"
    values:
      layout: default
      lang: "en"
```

But still not working.

**Comment by gguen** [comment]
Thanks to @parkr. Specify values in config.yml works correctly for subfolders after upgrading jekyll 3.0.1 to 3.1.1.

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least
three months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If you can still reproduce this error on the <code>3.1-stable</code> or <code>master</code> branch,
please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider building it first as a plugin. Jekyll 3 introduced
[hooks](http://jekyllrb.com/docs/plugins/#hooks) which provide convenient access points throughout
the Jekyll build pipeline whereby most needs can be fulfilled. If this is something that cannot be
built as a plugin, then please provide more information about why in order to keep this issue open.

Thank you for all your contributions.

**Comment by CGarces** [comment]
Tested with jekyll 3.2.1
Still not working.

Sample config file

```
collections:
  docs:
    output: true
    permalink: "/:title"
    lang: "default"

defaults:
  -
    scope:
      type: "docs"       
      path: "/es/"
    values:
      layout: default
      lang: "es"
  -
    scope:
      type: "docs"     
      path: "/en/"
    values:
      layout: default
      lang: "en"
```

Desired behaviour. docs inside "en" folder has a attribute lang equal to "en"

**Comment by CGarces** [comment]
I have uploaded again one test to help to reproduce the error
See https://github.com/CGarces/jeklly_path_issue

config_yml

```
defaults:
  -
    scope:
      type: "docs"       
      path: "_docs/es/"
    values:
      layout: default
      lang: "es"
  -
    scope:
      type: "docs"     
      path: "_docs/en/"
    values:
      layout: default
      lang: "en"
```

Layout

```html
<html>
<body>    
{% for doc in site.docs %}
  <div>
    doc.name = {{ doc.name }}
    doc.lang = {{ doc.lang }}
  </div>
{% endfor %}
</body>
</html>
```

Expected result

```html
<html>
<body>    
 <div>
    doc.name = test_es
    doc.lang = es
  </div>

  <div>
    doc.name = test_en
    doc.lang = en
  </div>

</body>
</html>
```

rendered, see https://github.com/CGarces/jeklly_path_issue/blob/master/_site/test_en/index.html

```html
<html>
<body>    
 <div>
    doc.name = test_es
    doc.lang = 
  </div>

  <div>
    doc.name = test_en
    doc.lang = 
  </div>
</body>
</html>
```
