### ISSUE TITLE
empty content document not appearing in collection loops

### ISSUE THREAD

**Issue by matallo** [jekyll/jekyll#4357]
**steps to reproduce**

in `_config.yml`

```
collections:
  webinars:
    output: true

defaults:
  -
    scope:
      path: ""
      type: webinars
    values:
      layout: webinars_item
```

create a `_webinars` folder with several documents, some with content some without content (but with front-matter) in the fashion below:

```
---
title: ...
description: ...
date: ...
register_url: ...
---

(optional content)
```

**actual behaviour**

only those with content will appear in the next loop, but not the whole collection

```
{% for webinar_item in site.webinars %}
  ...
{% endfor %}
```

even a `{{ site.webinars.size }}` would return only those who had content

**expected behaviour**

return all the documents even if they don't have content (I need the front-matter)

---

this is a change of behaviour from v2 (where it returned the whole collection) to v3, if this is expected, how do you suggest to achieve the expected behavior (not relying in separate `_data` files if possible)
