### ISSUE TITLE
Jekyll 3.1 breaks YAML frontmatter rendering in tag page layout when using jekyll-tagging plugin

### ISSUE THREAD

**Issue by arkfps** [jekyll/jekyll#4430]
As of Jekyll 3.1.0 all variables defined in YAML frontmatter of tag page layout when using [jekyll-tagging plugin](https://github.com/pattex/jekyll-tagging) silently expands to nothing. Breaking change or regression?

**Comment by pathawks** [comment]
Can you provide an example (or the source of a site) that builds correctly with 3.0 and incorrectly with 3.1?

**Comment by arkfps** [comment]
Here is a  minimal reproducible example (attached). The setup is the following:
* `Gemfile` contains

  ```ruby
  source 'https://rubygems.org'
  gem 'jekyll', '3.0.2'
  gem 'jekyll-tagging'
  ```
* `_config.yml` contains

  ```yaml
  gems:
    - jekyll/tagging
  tag_page_layout: tag_page
  and `tag_page_dir: tag
  ```
* `_layouts\tag_page.html` contains

  ```yaml
  ---
  layout: default
  title: Tag Page
  content: Tag Page Content
  ---
   ```
* `_posts/2016-01-31-welcome-to-jekyll.markdown` defines `tags: ['TEST_TAG']` in its frontmatter

After building the site and examining the content of `_site/tag/test_tag.html` you can see

```html
<title>Tag Page</title>

...

<p>Tag Page Content</p>
```

Now replace `gem 'jekyll', '3.0.2'` with `gem 'jekyll', '3.1.0'` in Gemfile, update the bundle and rebuild the site. In `_site/tag/test_tag.html` you now see

```html
<title>Your awesome title</title>

...

<p></p>
```
[test.zip](https://github.com/jekyll/jekyll/files/111253/test.zip)
