### ISSUE TITLE
Unclosed rouge highlighting 

### ISSUE THREAD

**Issue by tomasfejfar** [jekyll/jekyll#4432]
I have a post:

```md
---
layout: post
status: publish
published: true
title: This blog is now on Jekyll
date: '2016-01-31 00:00:00 +0200'
tags: []
excerpt: Some excerpt
---
This is not yet highlighted
{% highlight php linenos %}
test
{% endhighlight %}

This should not be highlighted, right? 
```
And it generates this:
![image](https://cloud.githubusercontent.com/assets/642928/12705876/d7a1651c-c878-11e5-9e2b-3a40f03ee9cd.png)

Actual HTML:
```
<p>This is not yet highlighted</p>

<div class="highlight"><pre><code class="language-php" data-lang="php">
    <table style="border-spacing: 0">
        <tbody>
        <tr>
            <td class="gutter gl" style="text-align: right">
                <pre class="lineno">1</pre>
            </td>
            <td class="code"><pre>test<span class="w"></span></pre>
            </td>
        </tr>
        </tbody>
    </table>


    This should not be highlighted, right?
</code></pre>
</div>

      <hr>
```

My config (relevant part):
```
permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:

  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge
  line_numbers: true
```

Could this be theme issue? And if so, how could I debug it? It seems to me like a problem in parsing the closing `endhighlight` tag...
