### ISSUE TITLE
Default values behave differently on OS X and GitHub Pages

### ISSUE THREAD

**Issue by MattiSG** [jekyll/jekyll#4441]
If I set the following values in `_config.yml`:

```yaml
defaults:
  -
    scope:
      path: ""	# means "all files"
      type: item	# targets a collection
    values:
      layout: item
      logo: img/default-logo.jpg
```

And, in a YAML front matter, I define the `logo:` property without a value.

Then, on OS X 10.11.3 with ruby 2.0.0p645 and Jekyll 3.1.1, I get `img/default-logo.jpg` as the value for `page.logo` while, on GitHub Pages, I get the empty string.

An example reproduction can be seen on the index page of [`sgmap/sgmap.github.io`](https://github.com/sgmap/sgmap.github.io/tree/4d47e527eb4eda6cc3f9bdac05f393fd588205c6) ([default value](https://github.com/sgmap/sgmap.github.io/blob/4d47e527eb4eda6cc3f9bdac05f393fd588205c6/_config.yml#L22), [value interpolation](https://github.com/sgmap/sgmap.github.io/blob/4d47e527eb4eda6cc3f9bdac05f393fd588205c6/_includes/startup.html#L2)).
