### ISSUE TITLE
Layout variables present on all pages

### ISSUE THREAD

**Issue by greenify** [jekyll/jekyll#4442]
For some reasons on Jekyll 3.1.1 the layout inheritance seems to be broken. For me all variables from any layout file (yes even if the layout file is not part of the inheritance chain) are populated into the `layout` hash.

`post.html`
```
layout: default
comments: true
```

-> layout.comments is `true` on all pages with `post` layout -> expected

`page.html`
```
layout: default
```
-> layout.comments is `true` on these pages too -> breaking error
This makes it impossible to set layout specific variables.

Workaround
---------------

I found the following workaround to work, however I still think that it's a major issue especially because this worked in Jekyll 2.

```
defaults:
  - scope:
      type: posts
      path: '_posts'
    values:
      layout: post
      comments: true
```
