### ISSUE TITLE
Defaults not available when iterating over posts

### ISSUE THREAD

**Issue by louwers** [jekyll/jekyll#4482]
The following works fine when I set `hidden` explicitly in the front-matter of a post:
```
{% for post in site.posts  %}
  {% if post.hidden %} this post is hidden {% endif %}
{% for post in site.posts  %}
```
However using, in `_config.yml`:
```yml
defaults
  -
    scope:
      path: "_posts/bookmarks"
    values:
      hidden: true
```
The 'this post is hidden' message is no longer being shown. I know my defaults targets the right posts and that the hidden tag is applied, I just can't access it when iterating over posts with a for loop. It doesn't seem to be a problem exclusive to the `hidden` parameter.

**Comment by parkr** [comment]
@louwers Your YAML is incorrect, and you require the `type` field:

```yaml
defaults:
  -
    scope:
      type: "posts"
      path: "_posts/bookmarks"
    values:
      hidden: true
```
