### ISSUE TITLE
Cannot specify default categories for certain paths

### ISSUE THREAD

**Issue by chasemccoy** [jekyll/jekyll#4506]
I just updated to Jekyll 3.1.1 from Jekyll 2.x, and I was previously using a unique file structure. In my `_posts` folder I had three different folders corresponding to 3 different categories on my site.

In my `_config.yml` file, I had these defaults set to add a corresponding category to the posts in each folder:

```
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "asides"
      type: "posts"
    values:
      category: asides
  -
    scope:
      path: "columns"
      type: "posts"
    values:
      category: columns
  -
    scope:
      path: "quotes"
      type: "posts"
    values:
      category: quotes
```

To clarify, the files in `_posts/asides/` should get the `asides` category, etc. After updating to Jekyll 3.x, this no longer to seems to work. On the index of my site I am trying to loop over posts with this category using `{% for post in site.categories.asides %}`, but this gives me output. 

I have searched for a solution to this and have found none, so I am assuming it is a bug somewhere in Jekyll. I looked at the upgrade guide but didn't see any mention of any changes that would affect this.
