### ISSUE TITLE
GFM input for Kramdown not working

### ISSUE THREAD

**Issue by ePirat** [jekyll/jekyll#4529]
I've already asked the Kramdown devs about it (see gettalong/kramdown/pull/68) as the following config doesn't work properly:

```yaml
kramdown:
  input: GFM
  syntax_highlighter: rouge
```

As seen above, it should use the Github Flavored Markdown mode, but isn't. The most obvious way I notice this, is that the fenced code blocks using <code>```</code> do not work.

Version: jekyll 3.1.1
