### ISSUE TITLE
permalink :title different in jekyll 3.0.3 for collection items but not mentioned in the docs

### ISSUE THREAD

**Issue by GeorgePhillips** [jekyll/jekyll#4538]
###### What version of Jekyll are you using (`jekyll -v`)?

2.40 vs 3.0.3
###### What operating system are you using?

OSX and CloudCannon
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
When migrating to 3.0.3 I followed the migration guide for our [documentation](https://github.com/CloudCannon/Documentation/commit/1a96b67da94e05fc27d323fea2e212d8b8d4e451). This worked as expected and decreased the build time significantly. However, the permalink structure for the collection items had changed. The permalink structure `/overview/:title/` used to actually take the title in the collection item and slugify it. In the latest version it just used the filename.

```
collections:
  overview:
    title: Overview
    permalink: /overview/:title/
    active_prefix: overview
    output: true
```
###### What did you expect to see?

I expected the :title to match 2.x versions when used in the permalinks. in 2.x it used the title from the collection item.
###### What did you see instead?

The :title used the slug from the filename instead.
