### ISSUE TITLE
defaults scope doesn't work

### ISSUE THREAD

**Issue by andyyou** [jekyll/jekyll#4604]
###### What version of Jekyll are you using (`jekyll -v`)?

v3.1.1

###### What operating system are you using?

osx 10.11.3

###### What did you do?

I am trying use defaults scope in `_config.yml` but doesn't work. For example I have a folder named `works` and I put some html file inside. I think Jekyll only have three types for content that will convert; `pages`, `posts`, and `draft` (If I misunderstand please correct me) so besides `posts` other content I want to use in ordinary html that will belongs to `pages` type. 

At first I put YAML front matter to HTML file to specify `layout` it's working fine, then I try to move configuration to `_config.yml` that never work.

Here is my settings 

```
defaults:
  -
    scope:
      path: "works"
      type: "pages"
    values:
      layout: "works"
      title: "NEW PAGE"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: css
      title: "New Post"
```

###### What did you expect to see?

![](http://i.imgur.com/iHp1VqV.png)

The code as follow

```

---
layout: 'works'
---
<p>works content</p>

```
###### What did you see instead?

But when I move settings to `_config.yml` and restart `jekyll serve` became

![](http://i.imgur.com/NNLV9OT.png)

There is no layout applied
