### ISSUE TITLE
how jekyll to support task lists?

### ISSUE THREAD

**Issue by AidanDai** [jekyll/jekyll#4681]
## Environment

the jekyll version:   jekyll 3.1.2
github pages:  [http://AidanDai.github.io]( http://AidanDai.github.io)
power by:  [jekyll-theme-EasyBook](https://github.com/laobubu/jekyll-theme-EasyBook) 

I create a blog on github by jekyll, and Build settings contains the following:

```
# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
```

## question

I want to use task lists, like useing it on [github](https://github.com/AidanDai/AidanDai.github.io/blob/master/_posts/2016-03-18-plan-for-2016.md) on my [blog](http://aidandai.github.io/archives/plan-for-2016), but ti is fails.

I atempt to searched, resulted it, but google no someting about this!  who can have easy method?
