### ISSUE TITLE
Feature request: remove item from array, by value or key

### ISSUE THREAD

**Issue by drumanagh** [jekyll/jekyll#4797]
This is something pretty simple that, as far as I can tell, can't be done right now.

For a simple example, let's say I have this array:

```
movies:
  - title: Jurassic Park
    year: 1993
  - title: Independence Day
    year: 1996
  - title: The Great Dictator
    year: 1940
```

If I want to add an item, that's easy. I can do `{{ movies | push: ... }}`.

But what if I want to, say, remove Independence Day from the list? I don't have any way to do that.

It's worth nothing that this somewhat overlaps with `where_exp` (e.g. you can do a negative boolean to match anything not of the intended value), but having a dedicated syntax for it that matches the other array operations would be a bit simpler.

Maybe something like `{{ array | remove: value }}` or `{{ array | remove_where: 'key', value }}`?
