### ISSUE TITLE
YAML variable rendering "on" as "true"

### ISSUE THREAD

**Issue by tombell** [jekyll/jekyll#4798]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.0.2

###### What operating system are you using?

OSX

###### What did you do?

```yaml
  - name: on
    definition: Stark.on(event, handler)
    description: bind a handler to a specific event.
    details: |
      The `on` function binds a handler function to an event. The `event` is a string of the event name. The `handler` parameter is a function (with a parameter depending on the event bound) with no return value.
    example: |
      Stark.on("starkDidLaunch", function() {
        Stark.log("Stark loaded...");
      });
```

```
## {{ site.data.stark.name }}

{{ site.data.stark.description }}

{% for func in site.data.stark.functions %}

### {{ func.name }}

**{{ func.name }}** `{{ func.definition }}` - {{ func.description }}

{{ func.details }}

{% highlight javascript %}
{{ func.example }}
{% endhighlight %}

{% endfor %}
```

###### What did you expect to see?

I expected to see the text "on" rendered.

###### What did you see instead?

I saw the text "true" rendered.
