### ISSUE TITLE
Case & Elsif statements don't seem to process YAML front matter.

### ISSUE THREAD

**Issue by markorapaic** [jekyll/jekyll#4812]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
OSX El Capitan

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Made the case statement below, which doesn't seem to work (even though I can't see anything wrong with what i've done):

```
        {% assign catIcon = project.categories %}
        {% case catIcon %}
          {% when 'illustration' %}
             <img src="/assets/illustration.svg" width="30" />
          {% when 'design' %}
             <img src="/assets/design.svg" width="30" />
          {% else %}
             Nothing here.
        {% endcase %}
```

When that didn't work, I tried a simple if then statement, which also didn't work:

```
        {% assign catIcon = project.categories %}
        {% if catIcon == 'illustration' %}
          <img src="/assets/illustration.svg" width="30" />
        {% elsif pcatIcon == 'design' %}
          <img src="/assets/design.svg" width="30" />
        {% else %}
          Nothing here.
        {% endif %}
```

Here is the `collections` portion of my `_config.yml` file, if that helps.
```
collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      feature_image: /assets/default_featured_image.jpg
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post
      categories:
      feature_image: /assets/default_featured_image.jpg
```

###### What did you expect to see?
I expected to see either the `illustration.svg` icon or the `design.svg` icon depending on which category was encountered. To elaborate further, a statement like `{{ project.categories }}` actually does work as expected in my template; the category renders without issue. It's only within the scope of a case statement or elsif statement that it stops working.

###### What did you see instead?
Instead I encountered the `Nothing here.` text. I've had a look through some of the issues to see if there was something similar to my issue - and I get the impression that there are general issues with layouts / liquid in version 3.x.x - is that the case?
