### ISSUE TITLE
`jekyll new` doesn't tell you to enter the directory

### ISSUE THREAD

**Issue by AnsonYao** [jekyll/jekyll#4834]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.3

###### What operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

input:
```
jekyll new abc
jekyll build
```

response: 

`Liquid Exception: Included file '_includes/icon-github.html' not found in abc/about.md`

###### What did you expect to see?
I have realized I need to cd to myblog in order to build. But It took me quite a while trying to fix the about.md and I hope the response can be more helpful in this case.

**Comment by ChaosCat** [comment]
@bigface A **symbolic link** (symlink) is just a file that contains reference to other file/s, nothing wrong with that error message the full one is this:
```yml
Configuration file: none
            Source: /home/elian/Documents/Development/Jekyll Sites
       Destination: /home/elian/Documents/Development/Jekyll Sites/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout 'post' requested in sandbox/_posts/2016-04-25-welcome-to-jekyll.markdown does not exist.
Liquid Exception: Included file '_includes/icon-github.html' not found in sandbox/about.md
```
As you can see the error simply says that when it checked the sub folder of the root of the project (which is in this case the root of the project itself), it found a markdown file, with the property of `layout: post` and it also had a request from `about.md` for a file in the `_includes` subdirectory of the folder where `about.md` is, but it didn't check deeper since the build command is designed *(I assume)* to check only to one folder depth for layouts and plugins, includes etc... thus, it didn't find the file names that the markdown files requested. **Which makes this error completely fine.**
