### ISSUE TITLE
HTML tag not outputted correctly during an unknown circumstance

### ISSUE THREAD

**Issue by KILL3RTACO** [jekyll/jekyll#4995]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---
- [x] I am on (or have tested on) ***Windows*** 10+

---
Forgive me for the slightly confusing title, I'm not even sure how to explain this properly due to the confusion its caused me.

I am making a GitHub pages site, each every project that I work on will have their own page, with a box on the right giving some basic meta (dependencies, short description, platforms it runs on, etc.). I am using yaml data files to store all this information. Some of the projects I have labeled "umbrella projects" - they are basically a project that contains sub-projects, and for this I created a simple include that renders a grid showing each of the sub-projects:

```html
<!-- _includes/project-grid.html -->
<div class='project-grid'>
  {% for id in include.projects %}
    {% assign project=site.data.projects[id] %}
    {% if include.no-children and project.parent %}{% continue %}{% endif %}
    <a href='/project/{{id}}' class='project-grid-link' title='{{project.description}}'>
      {% if project.nav-name %}{{project.nav-name}}{% else %}{{project.name}}{% endif %}
      {% include project-labels-short.html labels=project.labels %}
    </a>
  {% endfor %}
</div>
```
I basically give it some project ids and it renders them as part of the grid. If I only want to render projects that are umbrellas or standalone, I set `no-children=true` in the include call. When rendered, it creates something along the lines of this:

```html
<div class="project-grid">
  <a class="project-grid-link" href="/project/asc" title="The engine used by Ascension: Preamble">Asc
    <div class="project-labels-short"><span class="project-wip">W</span></div>
  </a>
  <a class="project-grid-link" href="/project/asc-public-util" title="Utils from Asc made explicitly public">AscPublicUtil
    <div class="project-labels-short">
      <span class="project-demo-available">D</span>
      <span class="project-wip">W</span>
    </div>
  </a>
  <a class="project-grid-link" href="/project/preamble" title="An Electron and Journey/Asc based game.">Ascension: Preamble
    <div class="project-labels-short"><span class="project-wip">W</span></div>
  </a>
</div>
```

To lessen the length of this issue, I will only show two of the projects in the data file, one being an umbrella/parent and one being a child:
```yml
#_data/projects.yml
bukkit-all:
  name: "Bukkit"
  nav-name: "Bukkit Projects"
  description: "Bukkit plugins that I've created"
  labels:
    - abandoned
    - umbrella
  languages: ["Java", "JSON"]
  platforms: ["bukkit"]
  children: ["itemmail", "taco-serialization", "mineopoly", "taco-api"]

taco-api:
  name: "TacoAPI"
  parent: "bukkit-all"
  description: "API containing tools and utility classes. Used by every Bukkit plugin I've made"
  languages: ["Java", "others"]
  platforms: ["bukkit"]
  labels:
    - mature
    - partially-abandoned
```

# Problem
All the project pages are markdown files with a specific layout, it helps speed the process so I don't have to write as much. So far, I have two umbrella projects listed, and both of these pages are going to use the include above. On one of them, it renders correctly. On the other, sort of. For some reason the tag's braces (<, >) get turned into literal braces (\&lt; ... \&gt;):
![](http://i.imgur.com/pMXsXha.png)

I thought that perhaps the rendering problem had something to do with it being the fourth element, so I removed 'taco-api' as one of the children of 'bukkit-all' (by removing it from the array). The result is this:
![](http://i.imgur.com/dpI3W30.png)

Now, the actual contents of 'bukkit-all.md' (which would be should at `/projects/bukkit-all` in the site) is not that lenghty:
```md
---
layout: project
project-id: bukkit-all
---
{% include project-grid.html projects=site.data.projects.bukkit-all.children %}
```

So I decided to see what happens if I simply change the extension from `md` to `html` and build again. The grid renders completely fine. What's going on here? Is there something wrong with the include file? I figured another possibility was the actual yaml for `taco-api`, which is why it's shown above, but I don't see anything wrong with it.
