### ISSUE TITLE
Jekyll throws exceptions when Rails finds an asset

### ISSUE THREAD

**Issue by illegalnumbers** [jekyll/jekyll#5004]
- [x ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x ] I am on (or have tested on) ***MacOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x ] It was another bug.

## My Reproduction Steps

I have an attached config file for a Rails project using Jekyll with Octopress as the blog. When Rails attempts to find an asset and load it I get:
```
undefined method `jekyll' for #<Sprockets::CachedEnvironment:0x007ffc44a6a0e8>
```

```
baseurl: "/blog"
gems:
 - jekyll-assets
assets:
  dirname: /blog/_assets
  baseurl: /blog/assets/
  sources: 
    - _assets/stylesheets
    - _assets/javascripts
    - _assets/images
  cachebust: hard
  js_compressor: uglifier
  css_compressor: sass

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
```

```
#config/initializers/blog.rb

Rails.application.config.after_initialize do
  Rails.logger = Logger.new(STDOUT)
  begin
    # make a spot for the site
    dest = Rails.root.join('public/blog')

    # generate the site
    Jekyll::Site.new(
      Jekyll.configuration({
        "config" => Rails.root.join('config', 'jekyll.yml').to_s,
        "source" => Rails.root.join('blog').to_s,
        "destination" => dest.to_s
      })
    ).process

    # the strange codes give the output color
    Rails.logger.info "\e[0;32;49mJekyll site built!\e[0m]]"
  rescue => e
    Rails.logger.error "\e[0;31;49mJekyll site build failed.\e[0m\n\e[0;33;49mError:\e[0m #{e}"
  end
end
```

```
## The Output I Wanted

No exceptions - my assets should serve
<!-- 
  Insert the output from the command. Alter it as little as you can.
  The minimum should be personal information. Though we normally don't log
  anything like that so there should be no need to alter it.
-->
