### ISSUE TITLE
Data files as a default collection

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#5207]
For historical reasons, we currently have three data types, each with their own reading and rendering logic:

* Pages
* Documents
* Data files

This causes headaches for anyone trying to build on top of Jekyll in any way that iterates over content, because logic has to be implemented two, often three times, in very different ways (as an example Document has a `path` method, while on Pages you need to call `File.join(@base, @dir, name)` to achieve the same result.

Then you get to data files, which unlike documents and pages, aren't distinct objects and are read directly into the site's config as a nested hash. You can't call `to_liquid` on them and there's no programatic way to get the document's path (since the key is sanitized). 

Now here's the silly thing: collection documents [can be YAML files](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb#L264), which begs the question: *why don't we just make data files a default collection*?

If I'm reading the code correctly, it should just be a matter of:

1. Teaching documents to [read in CSV files](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/readers/data_reader.rb#L53-L61)

2. Alias `site.data` to `site.collections.data.docs` for backwards compatibility

Theoretically, this should preserve existing behavior, but would allow each data file to be a distinct object and interacted with by plugins, not to mention, would allow us to DRY up the codebase a bunch.

See also https://github.com/jekyll/jekyll/issues/5064, a related issue on being able to disable default collections (which assumes `_data` *is* a collection).

/cc @jekyll/build

**Comment by shawnbot** [comment]
I couldn't find any reference to this in other issues, but would/could this address the desire to treat data files as collections, so that you could have, for instance, a page for each row in a CSV file? E.g. in a config:

```yaml
collections:
  parcels:
    # or maybe this could be a key in site.data?
    source: _data/parcels.csv
    output: true
    permalink: /parcels/:blkgroup/

defaults:
- scope:
    path: ''
    type: parcels
  values:
    layout: parcel
```
