### ISSUE TITLE
[NEW FEATURE] Several pagination paths

### ISSUE THREAD

**Issue by djcaesar9114** [jekyll/jekyll#5367]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---
- [ ] I am on (or have tested on) **_macOS**_ 10+
- [x] I am on (or have tested on) **_Debian/Ubuntu**_ GNU/Linux
- [ ] I am on (or have tested on) **_Fedora**_ GNU/Linux
- [ ] I am on (or have tested on) **_Arch**_ GNU/Linux
- [ ] I am on (or have tested on) **_Other**_ GNU/Linux
- [ ] I am on (or have tested on) **_Windows**_ 10+

---
- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.
## My Reproduction Steps

I entered `paginate_path: "blog/page:lang/page:num/"` in the `_config.yml` file.

## The Output I Wanted

I wanted to have, when my `lang` attribute is set to "en", a pagination like this: `blog/en/page1/`, and so on.

Instead, I have `blog/page:lang/page1/` and so on.

I think it would be a good feature to have several pagination for several languages, for example.

**Comment by vossavant** [comment]
I wholeheartedly endorse this feature request. While there is a plugin called `jekyll-paginate-multiple`, it is intended for multi-language sites and only works if you have a need for separate folders within your _posts_ directory.

It would be great if we could do something like this (in `_config.yml`):
```
collections:
  authors:
    title: Authors
    paginate_path: "/authors/page/:num"
  posts:
    title: Posts
    paginate_path: "/blog/page/:num/"
```

Right now, for instance, I have a template at `blog/index.html` and I am also paginating categories, so it would be nice if I could have my blog paginated like `paginate_path: "/blog/page/:num"` and my categories paginated like `paginate_path: "/page/:num"`. Since I am limited to one paginate path, my category URLs end up looking like `category/mobile/blog/page/2` instead of `category/mobile/page/2`.

**Comment by djcaesar9114** [comment]
@vossavant : the same for me. I use the same gem, but I think it could be easier to have this feature by default, particularly hen it comes to multilingual websites.
Here is what I have in my `_config.yml`:

```
paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/en/page:num/'
    sub_dir: '/en'
  - paginate: 5
    paginate_path: '/blog/fr/page:num/'
    sub_dir: '/fr'
```
