### ISSUE TITLE
 Liquid Exception: undefined method `includes_load_paths' Error message

### ISSUE THREAD

**Issue by twentytwoo** [jekyll/jekyll#5422]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
`jekyll serve`

EDIT: Every command with `jekyll` in it gives me:

```
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
```

However I am sure the error below is contained only to that jekyll site, I tested jekyll serve on another site, which outputs the above message, but it does infact build; therefore I can assume the issue is related somewhat to the plugins/dependencies.

---

So I woke up this morning and tried to do `jekyll serve` and this bug showed up, I updated all my plugins via `bundle update`, so all the dependencies are sound, I'm really unsure of what is wrong so I'm assuming this is a bug or perhaps something broken in my setup?

```
[git:reset@~/C/P/S/mktt-redux] $ jekyll serve                                                                                  10:57
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
Configuration file: /home/may/Code/Projects/Sites/mktt-redux/_config.yml
            Source: /home/may/Code/Projects/Sites/mktt-redux
       Destination: /home/may/Code/Projects/Sites/mktt-redux/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: undefined method `includes_load_paths' for #<Jekyll::Site:0x0000000264c5d8> in _layouts/default.html
jekyll 3.1.6 | Error:  undefined method `includes_load_paths' for #<Jekyll::Site:0x0000000264c5d8>
```

My config worked fine a few days ago, so maybe since I'm on Debian Sid (experimental) theres something up with the installation.

Help would be greatly appreciated!

## The Output I Wanted
Site actually builds

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by twentytwoo** [comment]
_config.yml

```
  # Main config file, put gems and other settings here.
# Site settings
title: milkyy.tk #top title
email: may.tt@protonmail.ch
permalink: none # url extension
description: > # this means to ignore newlines until "baseurl:"
  Personal blogging site utilising Jekyll, gh-pages, Bootstrap and the Liquid templating language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username: twentytwoo
timezone: UTC-1

# Build settings
markdown: kramdown
kramdown:
   input: GFM

# Syntax highlighter
highlighter: rouge

# Plugins
gems: [
     jekyll-watch,
     kramdown,
     rouge,
     jekyll-paginate
      ]

# ditaa plugin conf.
ditaa_output_directory: /assets/ditaa
ditaa_debug_mode: false

# in-browser posting (cms)
github:
    repo: twentytwoo/twentytwoo.github.io
    branch: master
```

The only plugin I'm using is [ditaa](https://github.com/matze/jekyll-ditaa)
