### ISSUE TITLE
where_exp and filters

### ISSUE THREAD

**Issue by drumanagh** [jekyll/jekyll#5545]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

Right now, `where_exp` is super-handy... unless you've got nested elements you want to work with.

For example, let's say I have `site.dinosaurs`:

```
- title: tyrannosaurus
  bone_locations:
    - location: Arizona
      bones_found: 6
    - location: New York
      bones_found: 12
- title: velociraptor
  bone_locations:
    - location: Texas
      bones_found: 2
    - location: Missouri
      bones_found: 9
- title: triceratops
  bone_locations:
    - location: Texas
      bones_found: 37
    - location: Arkansas
      bones_found: 119
```

Now I want to look up a particular subset based on this data. But, wait a minute! There's no way for me to get into the `bone_locations` hash.

```
{% assign particular_dinosaurs = site.dinosaurs | where_exp: "dinosaur", "dinosaur.bone_locations|map:'location' contains 'Texas'" %}
```

...doesn't work, because `where_exp` directly passes the contents along as a condition, which doesn't process filters.

It seems like there should either be some expanded processing here to allow this kind of data handling to work.
