### ISSUE TITLE
Generating non-html files

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5619]
Perhaps, I'm missing something, but I've been unsuccessful with this so far..
```
collections:
  trials:
    output: true
    permalink: /test/:path.xhtml
```
generates:
```
_site/test/doc1.xhtml.html
_site/test/doc2.xhtml.html
```
even though [this](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/page.rb#L26-L30), [this](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/page.rb#L85-L86) and [this](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/page.rb#L168-L170) together should not be doing the above..

/cc @jekyll/ecosystem

**Comment by parkr** [comment]
@ashmaroli These are not `Page` objects, but `Document` objects.

**Comment by ashmaroli** [comment]
I thought so.. but then why does
```
collections:
  docs:
    output: true
    permalink: /awesome/:basename:output_ext
```
return
```
jekyll 3.3.1 | Error:  The URL template doesn't have basename keys. Check your permalink template!
```
