### ISSUE TITLE
Theme gem installed from a git repo raises liquid exception

### ISSUE THREAD

**Issue by ysfjwd** [jekyll/jekyll#5633]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [x] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I am trying to make a new website, and want to keep the theme separate. In order to do that, I checked forked the minima theme, and renamed it here.

[Forked Theme](https://github.com/maherpk/maherpk-jekyll-them)

to reflect that in my configuration, Here is my Gemfile

```ruby
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.3.1"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"
gem "maherpk-jekyll-theme", git: "git@github.com:maherpk/maherpk-jekyll-them.git"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem 'github-pages', "105"
end
```

and this is my _config.yml

```yml
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
theme: maherpk-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
```

after doing

```sh
bundle install
bundle exec jekyll serve
```

i get this error

```log
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of nil into String in about.md
jekyll 3.3.1 | Error:  no implicit conversion of nil into String
```

the minute i change the theme back to minima, the site compiles fine. I believe this is because the git checked out theme is not able to find its way into jekyll.

I maybe wrong, but i think this is a bug.

thanks.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)
