### ISSUE TITLE
site.posts.size = 0, although there are posts in the folder

### ISSUE THREAD

**Issue by obendevski** [jekyll/jekyll#5849]
- [x] I believe this to be a bug, not a question about using Jekyll.

---
- [x] I am on (or have tested on) ***macOS*** 10+

- [x] It was another bug.

Previously i created a custom collection blog_posts and I came to realize later that pagination doesnt work with custom collections. When I tried to switch back to the "factory" settings and created a _posts folder, site.posts.size returns 0.

**Comment by pathawks** [comment]
Do any of the posts appear in the generated site?

Is your source public?

**Comment by obendevski** [comment]
the blog_posts do appear, the posts not. no, i'm afraid it's not public.

I followed the naming convention 2015-01-01-hello.md, still nothing.

When I do site.posts | inspect, it appears [].

**Comment by pathawks** [comment]
Can you provide a way for me to recreate this issue? Maybe provide a minimal site that exhibits this behavior?

**Comment by pnn** [comment]
can't reproduce either: 

https://pnn.github.io/jekyll-test/

https://github.com/pnn/jekyll-test/blob/master/_layouts/test.html

**Comment by obendevski** [comment]
The thing is the project was already in late stages.I created a new project yesterday and its working good. But the "old" one is still not working.

**Comment by pathawks** [comment]
> When I tried to switch back to the "factory" settings and created a _posts folder, site.posts.size returns 0.

> the blog_posts do appear, the posts not.

Wait, did you actually move all of your posts into the `_posts` directory? What is in the `_posts/` directory?

**Comment by obendevski** [comment]
i put some random 2015-01-01-hello-world.md files with frontmatter 

---
title: Hello world
---
random text.

Still nothing.

**Comment by pathawks** [comment]
What does your `_config.yml` look like?

**Comment by obendevski** [comment]
```
collections:
  blog_posts:
    output: true
    permalink: /blog/:path/
  jobs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job
  - scope:
      path: ""
      type: blog_posts
    values:
      layout: blog
```
