### ISSUE TITLE
Jekyll hates Ableton? collection `Ableton`: a magic word generates long compile time

### ISSUE THREAD

**Issue by leico** [jekyll/jekyll#5938]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

### Detail
when Collections directory named `_Ableton` and

```yaml
collections:
  any:
    output: true
  other:
    output: true
  collections:
    output: true
  Ableton:
    output: true
``` 

in `_config.yml`, no error but generate long time.

When directory name changed `_Test` and `_config.yml` also changed

```yaml
collections:
  any:
    output: true
  other:
    output: true
  collections:
    output: true
  Test:
    output: true
``` 

generate time only 5sec.(when named `_Ableton` generate 720sec)
My computer is wrong I guess first. but github pages also says Page build timed out. 

###  source data

https://github.com/leico/TechnicalNote2/tree/4a3b9a6396412c35726ae807fb0a47080f06b4ea

now `_Ableton` directory same as `_VirtualBox`, one markdown and some image files.
Please try to change `_Ableton` to `_Test` and build.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)
