### ISSUE TITLE
Add tag list for collection

### ISSUE THREAD

**Issue by Laoujin** [jekyll/jekyll#6085]
- [x] This is a feature request.

Currently tags and categories only contain those from posts and not from custom collections.

I've changed[ jekyll-archives](https://github.com/jekyll/jekyll-archives) locally to do exactly this. I want to elaborate a little and create a pull request if this functionality is desired?

**My proposal:**
By default, nothing changes as to not break existing sites.

In config.yml
```
collections:
  col1:
    output: true
    output_tags: true # both default to false
    output_categories: true
```

This has been requested before:
https://github.com/jekyll/jekyll/issues/5339
https://github.com/jekyll/jekyll/issues/3284
