### ISSUE TITLE
Jekyll Build Warning. 

### ISSUE THREAD

**Issue by kousherAlam** [jekyll/jekyll#6123]
I'm using jekyll v=3.4.3 and it gives me the warning like this: 
![capture](https://user-images.githubusercontent.com/14360099/26883100-0612bc2e-4bbe-11e7-873d-0591bec104f9.PNG)

How can I solve it ????
I'm using ruby : 2.3.3p222
gem : 2.5.2

**Comment by DirtyF** [comment]
HI @kousherAlam I don't know if you use a theme, but your `_layouts` folder only contains a `default` layout, you can only use that layout for now in your posts.

**Comment by DirtyF** [comment]
Please rather ask your question on https://talk.jekyllrb.com, the place to get help on Jekyll. This repo is intented for core development only.

**Comment by kousherAlam** [comment]
I'm not using any theme...

**Comment by kousherAlam** [comment]
Please tell me, are you tell me to print the post in `_layouts/default.html` ???

**Comment by DirtyF** [comment]
so simply use `layout:default` front matter variable in your markdown files stored in the `_posts` folder.

You can make it the default in your `_config.yml`:

```yaml
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
```

Defaults is documented: https://jekyllrb.com/docs/configuration/#front-matter-defaults
