### ISSUE TITLE
Permalink can't contain unicode

### ISSUE THREAD

**Issue by jpeg729** [jekyll/jekyll#6133]
```
collections:
  activites:
    output: true
    permalink: /activités/:name/
```
gives the error
```
jekyll 3.0.3 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
```
If I remove either `output: true` or the accent in the permalink it works fine.
