### ISSUE TITLE
Jekyllrb v3.5.0 - plugins_dir OR plugins ??

### ISSUE THREAD

**Issue by 7php** [jekyll/jekyll#6195]
- [x ] I believe this to be a question about using Jekyll.
- [x ] I updated to the latest Jekyll v3.5.0
- [x ] I ran `jekyll doctor` to check my configuration

---

- [x ] I am on (or have tested on) ***macOS*** 10+

---
/cc @jekyll/stability

Hi, I have tried Jekyllrb `v3.4.5` and `v3.5.0` and I see a discrepancy with the `plugins` in `_config.yml`

In `v3.4.5`, on terminal, I see the message: **"plugins deprecated, use plugins_dir"**.
It works.
BUT with `v3.5.0`, `plugins_dir` does not work.

So anyone can clarify this please..

**Comment by DirtyF** [comment]
Both options are not to be confused and do not receive the same type value.

- `plugin_dir` is the default path to the plugins directory `./_plugins` by default IIRC and should be given a path  (string).

-  `gems` is the name given to the _array_ that lists all plugins packaged as gems used by Jekyll.  Since Jekyll `3.5.0` this sequence has been renamed to `plugins` because that's what it is : a list of plugins used by Jekyll. 

So from Jekyll 3.5.0 you should have the following `_config.yml`:

```yaml
plugins_dir: ./_scripts

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
```

With a previous version of Jekyll like 3.4.5: 

```yaml
plugins_dir: ./_scripts

gems:
- jekyll-avatar
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
```
