### ISSUE TITLE
collections_dir does not work.

### ISSUE THREAD

**Issue by adam-arold** [jekyll/jekyll#6656]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I am on (or have tested on) ***Windows*** 10+
- [x] I was trying to build.

## My Reproduction Steps

I was running `jekyll build`.
I used `collections_dir: collections` in my `_config.yml`
I added some collections to my config so it looks like this:

```yaml
collections_dir: collections
collections:
  meetups:
    output: true
    permalink: "/events/:collection/:name"
  conferences:
    output: true
    permalink: "/events/:collection/:name"
  workshops:
    output: true
    permalink: "/events/:collection/:name"
```

After `jekyll build` ran I saw no collections in the resulting directory structure.

My collections were in the `collections` folder in `collections/_meetups`, `collections/conferences` and `collections/workshops` respectively.

If I set back `collections_dir` to `.` and move my collections to the root they properly get generated into my output folder. Seems like that `collections_dir` does not work in the way it is intended.
