### ISSUE TITLE
No _config.yml or GEMFILE when using jekyll new --blank

### ISSUE THREAD

**Issue by davatron5000** [jekyll/jekyll#6693]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

* Run `jekyll new myblog --blank`

## The Output I Wanted

**Expected:** A `GEMFILE` and a `_config.yml`. Running `jekyll doctor` throws a warning saying "You should probably a have a Configuration file."

**Actual:** Just empty folders.

There's no "sample _config.yml" that I could find on the website, so rolling your own is quite difficult. It'd be nice if Jekyll provided one like back in its pre-theme days. Or maybe it's a `--no-theme` flag where you get posts and templates without the `minima` dependency. I know a lot of folks who would rather roll there own theme. I think it should be the default, IMO. and you opt into themes like `--theme=minima`.

**Comment by ashmaroli** [comment]
I had once upon a time released a ["plugin" rubygem](https://github.com/ashmaroli/jekyll-plus) that extended Jekyll's `new` command to use a `--theme` option.
Once installed, you get a new program `jekyll+` that floats a couple of new commands in addition to existing Jekyll commands..

```
jekyll+ new-site awesome blog --theme minimal-mistakes-jekyll
```
would create a new Jekyll directory pre-configured to use `minimal-mistakes-jekyll` theme,,
More info in the Usage section of the repo..

**Comment by DirtyF** [comment]
👋 Would the folllowing help?

Jekyll defines a lot a default config options for you, a minima config file would be: 

```yaml
# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: My Website
description: "A short description of your project"

url: # (optional) https://example.com, defaults to http://localhost:4000 in development

permalink: date # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

# timezone: America/Los_Angeles # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# theme: minima 
# look for themes on https://github.com/topics/jekyll-theme and https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme

# Files to excludes from your website
# exclude:  
# - .gitignore
# - CNAME 

```

Thing is with Jekyll, you don't need a lot of configuration to get started.

A minimal `Gemfile` would be:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 3.7"
```

You can do something similar with bundle:

```sh
bundle init
bundle add jekyll
```

Let us know if that would help.
