### ISSUE TITLE
contentful import issue using mapper

### ISSUE THREAD

**Issue by KochuraniT** [jekyll/jekyll#6715]
i got the error **```jekyll 3.7.0 | Error:  undefined method `gsub' for #<Hash:0x000000058f0318>```** on `rake build` command, and the following is my _config.yml file contents:

```yaml
title: The Akhlaquna Award
description: To promote the Prophet's universal and inclusive moral behaviors.
url: "https://akhlaquna.qa" # the base hostname & protocol for your site, e.g. http://example.com

# Plugins
# https://github.com/jekyll/jekyll-seo-tag
plugins:
  - jekyll-seo-tag

# Conversion
markdown: kramdown

# Timezone
timezone: Asia/Qatar
# Serving
baseurl: "" # the subpath of your site, e.g. /blog

# Outputting
permalink: pretty

# Markdown Processors
kramdown:
  auto_ids: true # Auto-generate ID's for headings
  smart_quotes:   lsquo,rsquo,ldquo,rdquo

contentful:
  output: true
  spaces:
    - media: 
        space: 44ydup5yaty2
        access_token: 395877c3c9585dad49c1db82980d55fd80e78d2006633e9683a4e099a65fc6fa
        cda_query:
          content_type: 'media'
        all_entries: true
    - sponsers: 
        space: y75wkvmcwl0y
        access_token: 0777f9000166ba1791c35c9493df0715133a586300ad0252f555741962d78096
        cda_query:
          locale: '*'
          content_type: 'sponsers'
        all_entries: true
    - juries: 
        space: y75wkvmcwl0y
        access_token: 0777f9000166ba1791c35c9493df0715133a586300ad0252f555741962d78096
        # custom mapper
        # because jekyll-datapage_gen needed field name as page not as title.en-US        
        cda_query:
          locale: '*'
          content_type: 'jury'
        all_entries: true
        content_types:
          jury: PageMapperAR
    - gallery: 
        space: y75wkvmcwl0y
        access_token: 0777f9000166ba1791c35c9493df0715133a586300ad0252f555741962d78096
        cda_query:
          locale: '*'
          content_type: 'gallery'
        all_entries: true    

# Generate pages from Contentful data files
# Arabic is placed in /ar folder and using a different template
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.juries.jury'
    template: 'jury'
    name: 'page'
    dir: 'jury'
```
