### ISSUE TITLE
Arrays with key 'no' do not parse

### ISSUE THREAD

**Issue by seige13** [jekyll/jekyll#6796]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] It was another bug.

## Reproduction Steps

While using the [multiple languages plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin), I created an array of languages in the format (removed items for brevity):

```
langs:
  bg: Български
  cs: Česky
  da: Dansk
  en: English
  no: Norsk
```

when trying to translate these key - value pairs, it was returning a blank result for the Norwegian language (no). I believed this to be an issue with the plugin until I had copied the same array into the `_config.yml` file. Then using `{{ site.langs.no }}` anywhere on my site, it returns a blank result. Additionally, if you just added `no: test string` in the `_config.yml` and wanted to output `{{ site.no }}` this still fails and there is no output as well. 

### Edit

It seems if you do: 

```
langs:
  bg: Български
  cs: Česky
  da: Dansk
  en: English
  'no': Norsk
```

And use `{{ site.langs.no }}` the string will correctly parse. Not sure why this is? Maybe a reserved keyword
