### ISSUE TITLE
nested for loop is behaving strangely

### ISSUE THREAD

**Issue by lukepighetti** [jekyll/jekyll#6942]
team.md
```
---
layout: team
title: Team
permalink: /team/

team:
  - name: Dev
    tagline: We dev things
  - people:
    - name: John Adams
      title: title

    - name: John Smith
      title: title

    - name: person1
      title: title


  - name: Design
    tagline: We design things
  - people:
    - name: John Adams
      title: title

    - name: John Smith
      title: title

    - name: John Maria
      title: title

---

```

team.html
```
---
layout: default
---

{% for group in page.team %}
header

  {% for person in group.people %}
    person
  {% endfor %}

footer
{% endfor %}
```

output
```
header
footer

header
  person
  person
  person
footer
```

expectedoutput
```
header
  person
  person 
  person
footer
```
*repeated one more time*
