### ISSUE TITLE
Syntax Highlighting 

### ISSUE THREAD

**Issue by iphton** [jekyll/jekyll#7068]
About the syntax highlighting in Jekyll , how it'll appear on site. I observed that there are couple of ways we can do this like what `jekyll` introduced or markdown style. Now, as familiar for me and comfortable i like to use markdown style. Now, when i view the outcome on web i found like following - Is this how it appear ? I mean, just take a look the border around code and moreover the syntax is like more foggy or unclear. The same look appear if i use `jekyll` style though.

![www](https://user-images.githubusercontent.com/17668390/41204089-f5bfaa64-6c94-11e8-8549-8d71e1fb2cba.JPG)

Here is my  `_config.yml` file 

```
# The release of Jekyll Now that you're using
version: v1.2.0

theme: minima

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: pygments #rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
```
