### ISSUE TITLE
sub-collection documentation not found

### ISSUE THREAD

**Issue by Gl4di4torRr** [jekyll/jekyll#7347]
## Motivation

I have not found a good doc on how to create a sub collection.

## Suggestion
For example, in the picture, I have the collection` Developer Guide`. I would like to create a sub-collection, `routes`, but am unable to find a good example on [jekyll docs](https://jekyllrb.com/docs/)

<img width="209" alt="screen shot 2018-11-02 at 7 55 22 am" src="https://user-images.githubusercontent.com/10929182/47914129-d66f6f80-de74-11e8-96b9-f44cfe58de40.png">

**Comment by DirtyF** [comment]
Looks like what you call subcollection is content grouped under a page.
You want to something à la Bootstrap maybe? https://getbootstrap.com/docs/4.1/layout/overview/

**Comment by Gl4di4torRr** [comment]
@DirtyF that's basically what i ended up doing.

I was thinking about doing something like

```
collections:
  dev_guide:
    display_name: Developer Guide
    output: true
    order: 1
    collections:
      routes:
          ...
```
