### ISSUE TITLE
Allow configuring 'future' metadata for individual collections

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#7460]
## Summary

Currently, `future` config key is global and affects all collections in the site simultaneously. It would be awesome if users were able to exert finer control on which collections with future-dated documents should be iterable / renderable.

## Motivation

This comment by @pathawks :point_right: https://github.com/jekyll/jekyll/pull/6506#issuecomment-340675231

> I think we might consider making future available as a per-collection option.
Perhaps I don’t want my site built with future blog posts, but do want future events.
I think the current future option was added when posts were the only dated content. That is no longer the case.

## Guide-level explanation

- Ideally, `site.future` would be marked as deprecated with a fallback to automatically setting `collection.metadata["future"]` automatically set to `false (default) or true`. But we could also continue using this key as a global override.
- Usage:
  ```yaml
  future: true # all collections are configured with this global override
               # same behavior as in Jekyll 3.x
  collections:
    posts:
      future: true # renders and writes future-dated posts i.e. {{ site.posts }} will have
                   # future-dated posts and they will get written to `_site` directory.
    members:
      output: true
      future: false # does not render / write future-dated documents i.e. {{ site.members }}
                    # will not show future-dated docs nor will they get written to the `_site`
                    # directory.
    events:
      output: true
      future: "read-only" # future-dated docs can be accessed via {{ site.events }} but
                          # will not be written to the `_site` directory.
  ```
- Basically, the metadata key expects three values: **`true`**, **`false`** or **`read-only`**

## Drawbacks

- Added complexity in sites with numerous collections

**Comment by nhoizey** [comment]
I like this feature description.

However, I don't understand which value I would have to use to fix my issue #7458.

If this is `output: true` and `future: false`, I guess `does not render / write future-dated documents` should be changed to `does not render / write future-dated documents, neither show them in {{ site.events }}`.

**Comment by nhoizey** [comment]
Even if it changes everything, I guess this could be nice to have one single setting:

- `output: none`
- `output: past`
- `output: all`

I think page generation and item listing in Liquid loops should be consistent (see [my comment in #7458](https://github.com/jekyll/jekyll/issues/7458#issuecomment-451397112)), but an additional setting could be used:

- `loop: none`
- `loop: past`
- `loop: all`

Default value would be synchronized with the `output` setting.

**Comment by ashmaroli** [comment]
@nhoizey I've updated the spec with your suggestion.
But I don't see how setting `output: past` would convey the intention that the user does not want to be able
to iterate through future-dated docs in that collection in their Liquid Templates..

**Comment by nhoizey** [comment]
@ashmaroli that's why I added the `loop` setting

**Comment by DirtyF** [comment]
We should stick to Jekyll's philosophy: convention over configuration. 
Therefore posts and documents should behave the same : 

- posts and documents with a future date are not published by default
- when `future` option is globally set to true, posts and documents are accessible in Liquid loops

**Comment by ashmaroli** [comment]
@DirtyF ..and what about when `future` option is globally set to default `false` but with future-dated-posts and future-dated-documents?

**Comment by ari** [comment]
Is this discussion just a special case of a "filter" concept for collections? That is, there is some property by which collection documents are filtered before deciding to output them.

    filter: 'doc.date < time.now'

That's the concept that exists at the moment by default. Could this be made explicit and overridden in arbitrary ways?

**Comment by A1Liu** [comment]
Could the `published` attribute be modified to acheive the same effect as described above? i.e. published has 3 settings (similar to @nhoizey 's suggestion):

```yaml
published: null
published: true
published: false
```

Where `null` is the default behavior and behaves like `published: true` does now, `published: false` has the same behavior, and the new `published: true` forces document output.

Then, to achieve granularity with collections you would apply the value as a collection default value:

```yaml
defaults:
  -
    scope:
      type: "myfiles"
    values:
      published: true
```
