### ISSUE TITLE
HTML doesn't display correctly when mixed with Liquid in Markdown files

### ISSUE THREAD

**Issue by SpaceboyRoss01** [jekyll/jekyll#7623]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |Arch Linux|
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

```
{% for post in site.posts %}
  {% if post.categories contains "Projects" %}
    <div class="row">
      <div class="box">
        <h1><a href="{{ post.url }}">{{ post.title }}</a></h1>
        <sub>Posted: {{ post.date | date_to_string }}</sub>
        <p>{{ post.content | split: "." | first | strip_html }}</p>
      </div>
    </div>
  {% endif %}
{% endfor %}
```
This code above to be converted to the HTML bellow.
```
<div class="row">
  <div class="box">
    <h1><a href="/projects/2019/04/11/desktop-project-started.html">Desktop Project Started</a></h1>
    <sub>Posted: 11 Apr 2019</sub>
    <p>Today, I started my Linux desktop project for Computer Science Projects at school</p>
  </div>
</div>
```

## Current Behavior

Page renders as this:
![image](https://user-images.githubusercontent.com/19699320/56381669-65c1d280-61ca-11e9-99a2-3ae6c9cf9293.png)

## Code Sample

`projects.md`:
```
{% for post in site.posts %}
  {% if post.categories contains "Projects" %}
    <div class="row">
      <div class="box">
        <h1><a href="{{ post.url }}">{{ post.title }}</a></h1>
        <sub>Posted: {{ post.date | date_to_string }}</sub>
        <p>{{ post.content | split: "." | first | strip_html }}</p>
      </div>
    </div>
  {% endif %}
{% endfor %}
```

`_config.yml`:
```
title: "Spaceboy Ross"
description: "I’m Spaceboy Ross, also known as Tristan Ross, I’m a high school student from the Pacific Northwest in the United States. I do lots of programming and YouTube, the latter is less frequent due to school. I also go camping with Boy Scouts which is fun even though I’m aging out this year, I hope to continue to be involved. My daily driver operating system is Arch Linux and it’s the first rolling distro I’ve ever used. The top three things everyone needs to know about me are that I love girls who are tomboy a lot, I wear trenchcoats a lot, and I do a lot of programming."
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true
  html_to_native: true
  remove_block_html_tags: false
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
       path: ""
    values:
      layout: "default
```
