### ISSUE TITLE
Unable to execute "Jekyll serve" due to Invalid argument @ dir_s_mkdir

### ISSUE THREAD

**Issue by Blackbird2Raven** [jekyll/jekyll#7639]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   Windows 10        |
| `jekyll`         | 3.7.2     |
| `github-pages`   | |

---

## Current Behavior

 I am unable to execute the command "jekyll serve" as it is throwing up an error as shown below. I think it's adding a special character to the file path(which is not allowed in windows) within `_site` folder:
```
C:\website\dnifweb>bundle exec jekyll serve -t
Configuration file: C:/website/dnifweb/_config.yml
            Source: C:/website/dnifweb
       Destination: C:/website/dnifweb/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': Invalid argument @ dir_s_mkdir - C:/website/dnifweb/_site/https: (Errno::EINVAL)
        from C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
        from C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
        from C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
        from C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
        from C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:191:in `each'
        from C:/tools/ruby24/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/convertible.rb:229:in `write'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:208:in `block in write'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:329:in `block (2 levels) in each_site_file'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:328:in `each'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:328:in `block in each_site_file'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:327:in `each'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:327:in `each_site_file'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:207:in `write'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/site.rb:75:in `process'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:93:in `start'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/exe/jekyll:15:in `<top (required)>'
        from C:/tools/ruby24/bin/jekyll:23:in `load'
        from C:/tools/ruby24/bin/jekyll:23:in `<main>'

```

**Comment by ashmaroli** [comment]
@Blackbird2Raven Yes the issue is due to an incorrect filepath: `C:/website/dnifweb/_site/https:`
What are the contents of your config file and Gemfile?

**Comment by Blackbird2Raven** [comment]
@ashmaroli here you go:
- contents of`_config.yml`:
```
baseurl: "http://localhost:4000/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site



include:
    - _pages

collections:
  docs:
    output: true
  videos:
    output: true

# Build settings
markdown: kramdown
permalink: /:categories/blog/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

paginate: 4
paginate_path: /blog/page:num/

encoding: utf-8
sass:
    style: compressed

exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
```

2. Contents of `Gemfile` are:
```
source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate'
  gem 'jekyll-redirect-from'
  # gem 'html-proofer'
end

```
