### ISSUE TITLE
defaults not processed for collection pages when output is true

### ISSUE THREAD

**Issue by jonhoo** [jekyll/jekyll#7744]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | 3.8.5     |
| `github-pages`   | 198     |

---

## Expected Behaviour

I am trying to set a default layout for all outputs for a collection using:

```yaml
collections:
  episodes:
    output: true
defaults:
 - scope:
     path: ""
     type: "episodes"
   values:
     layout: episode
```

I expected all items in the `episodes` collection to be rendered using `_layouts/episode.html`.

## Current Behavior

The items are rendered using `_layouts/post.html`. This happens even with:

```yaml
defaults:
 - scope:
     path: ""
   values:
     layout: episode
```

It also appears that I cannot override this directly in the metadata for the collection:

```yaml
collections:
  episodes:
    layout: episode
    output: true
```

As far as I can tell, the _only_ way to get a different layout for these is to directly specify `layout: episode` in the front matter for each episode, which isn't ideal.

Overwriting _other_ values than `layout` works just fine. For example, if I write

```yaml
defaults:
 - scope:
     path: ""
     type: "episodes"
   values:
     foo: bar
```

And print `{{ page.foo }}` in `_layouts/post.html`, it correctly prints "bar".

**Comment by uberfuzzy** [comment]
Take the `path: ""` out of your scope. You dont need it if you are using the `type` from the collection. Items from collections dont have a path at all. Its trying to match both.

It works fine in stock 3.8.5, I'm doing the exact thing from your examples.

Its more likely something hinky in GitHub pages setting/overriding the layout, maybe because of a default theme?

**Comment by jonhoo** [comment]
I tried with out `path: ""` and the same issue occurred.

It seems quite likely that this is an issue with the GitHub connection specifically, though I'm not entirely sure why.

**Comment by monkeywithacupcake** [comment]
Is it possible that this is a spacing thing for .yml? My collection stuff is all indented under collections (and defaults under specific ones), but your defaults looks to be at the same point?
```
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  categories:
     output: true
```
