### ISSUE TITLE
Configuration: Output Line Numbers for Markdown-style Code Tags

### ISSUE THREAD

**Issue by fer-rum** [jekyll/jekyll#7859]
## Goal
When writing code in Markdown-style tags like

    ```some-language
      some code
      second line
    ```
the result should be rendered with line numbers.

## Restrictions
Using the `highlight` liquid tags is not an option, due to
* Lack of user acceptance (3rd party blog authors)
* Resulting HTML generated by _Rouge_ is awful

Having line numbers on a single code line is acceptable  

## Suspected Solution
There are several different [_Rouge_ formatters](https://github.com/rouge-ruby/rouge#formatters) and _HTMLLinewise_ was suggested to yield the desired results without distinguishing between single-line and multi-line code. However I was not able to convince _Jekyll_ to pass the appropriate option to _Rouge_ consistently. Sometimes the changes have no effect and sometimes the formatter gets selected and crashes with an exception.
Does the order in which I pass the options matter?
(Yes, I restarted `jekyll serve` after changing the configuration.)

## Attached
_config.yml
```yml
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    formatter: HTMLLinewise
    span:
      line_numbers: false
    block:
      line_numbers: true
```
