### ISSUE TITLE
'categories' front matter defaults not processed for non-collection pages

### ISSUE THREAD

**Issue by JinsYin** [jekyll/jekyll#7876]
## Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     MacOS       |
| `github-pages`   | Latest     |

Directory Structure:

```bash
├── _config.yml
├── _layout
│   └── doc.html
├── _posts
│   └── 2019-01-01-hello.md
├── git
│   └── github
│       └── index.md
└── index.html
```

`_config.yaml`:

```yaml
...
defaults:
  - scope:
      type: "posts"
    values:
      layout: doc
      categories: [blog] # -_-
  - scope:
      path: "git/github"
    values:
      layout: doc
      categories: [github] # -_-
...
```

`index.html`:

```html
<!-- Print all categories -->
{% for category in site.categories %}
  <h3>{{ category[0] }}</h3>
{% endfor %}

<hr>

<!-- Print the 'categories' front matter of all pages containing `git/` -->
<ul>
{% assign html_pages = site.html_pages | where_exp: "item","item.path contains 'git/'" %}
{% for doc in html_pages %}
    <li>{{ doc.path }} | {{ doc.categories }}</li>
{% endfor %}
</ul>
```

---

## Expected Behaviour

Expected build results:

```bash
$ tree _site/
├── blog/
├── github/
```

Expected `index.html`:

```html
<h3>blog</h3>
<h3>github</h3>

<hr>

<ul>
  <li>git/github/index.md | github</li>
</ul>
```

---

## Current Behavior

Current build results:

```bash
$ tree _site/
├── blog/
├── git/github/
```

Current `index.html`:

```html
<h3>blog</h3>

<hr>

<ul>
  <li>git/github/index.md | github</li> <!-- Only here is expected -->
</ul>
```

---

## Problem statement

Non-collection page does not fully support setting 'categories' front matter defaults.
