### ISSUE TITLE
Incorrect Line Breaks with Code Section

### ISSUE THREAD

**Issue by Merikanto** [jekyll/jekyll#7886]
So when I use the the code section in Jekyll (with Github Pages, Kramdown), sometimes I get incorrect line breaks. For example:

Normally a shell script should look like this:

```shell
for n in {0..4}; do
	if [[ $n == 2 ]]; then
		continue	
	fi
	echo $n
done

```

However, it looks like this in the renderer:

```shell
for n in {0..4}; do if [[ $n == 2 ]]; then continue  fi  echo 
$n done
```

This is my config for the page:

```
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    hard_wrap: true
    css_class: 'syntax'
```
I wonder which part went wrong! **I submit the issue under Kramdown's repo, but the people there said it's not really Kramdown's problem**. Thanks!
