### ISSUE TITLE
Syntax highlighting with Rouge: Inconsistencies between GitHub Pages and localhost.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [jekyll/jekyll#7929]
Note: I'm not sure if I should report this in a different repo (rouge, maybe?). If I should, please let me know and I'll gladly move it.

I'm also not sure if this is a duplicate of #6448. I've tried both Markdown's triple-backticks and Liquid's highlight directive, and neither one produce the right colors.

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Windows 10           |
| `jekyll`         | ~> 3.8.5 |
| `github-pages`   | Latest     |

---

## Expected Behaviour

I'd expect the localhost syntax highlighting to match the syntax highlighting on GitHub pages.

## Current Behavior

On local:

![image](https://user-images.githubusercontent.com/19352442/70285495-b7d55980-1795-11ea-9e50-85c0fd03d36a.png)

On GitHub Pages:

![image](https://user-images.githubusercontent.com/19352442/70285539-ccb1ed00-1795-11ea-83de-7e78b48fa895.png)

The class names on local seem to be off for whatever reason.

## Code Sample

Here's the blog post in question:

https://raw.githubusercontent.com/AleksandrHovhannisyan/aleksandrhovhannisyan.github.io/master/_posts/dev/2019-12-03-how-to-set-up-react-typescript-ant-design-less-css-modules-and-eslint.md

## Additional Info

Config:

```yml
title: Aleksandr Hovhannisyan
author: Aleksandr Hovhannisyan
description: "I'm a software developer who's passionate about tinkering with code, solving problems, and having fun. Get in touch!"
keywords: [Aleksandr Hovhannisyan, github pages resume, github pages portfolio, github pages personal website]
url: "https://aleksandrhovhannisyan.github.io/"
github_username: AleksandrHovhannisyan

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      showOnNavbar: true
      layout: "default"
  -
    scope:
      path: "_pages/categories"
      type: "pages"
    values:
      showOnNavbar: false
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:title/
  -
    scope:
      path: "_posts/dev"
    values:
      needsCodeFont: true
      categories: [Dev]
  -
    scope:
      path: "_posts/cs101"
    values:
      needsCodeFont: true
      categories: [CS101]
  -
    scope:
      path: "_posts/gaming"
    values:
      categories: [Gaming]
  -
    scope:
      path: "_posts/music"
    values:
      categories: [Music]


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
```

Gemfile:

```
source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.8.5"

# For GitHub Pages
gem "github-pages", group: :jekyll_plugins
gem 'jekyll-sitemap'

# Syntax highlighter
gem 'rouge'

# Addressing the reported GitHub Pages severe vulnerability
gem "nokogiri", ">= 1.10.4"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
```

Note that I tried adding the `rouge` gem to my Gemfile, ran `bundle`, included `highlighter: rouge` in my config, restarted, and the wrong syntax highlighting still persisted.
