### ISSUE TITLE
HTML Canvas tag converted to <div>&lt;canvas id=canvas&gt;&lt;/canvas&gt;</div>

### ISSUE THREAD

**Issue by goktug97** [jekyll/jekyll#7962]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Arch Linux    |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

```html
<div><canvas id=canvas></canvas></div>
```
Should be converted to canvas element

## Current Behavior
In page source it is converted as
```
<div>&lt;canvas id=canvas&gt;&lt;/canvas&gt;</div>
```

## Code Sample

Page is live at
https://goktug97.github.io/jekyll/update/2020/01/04/welcome-to-jekyll.html

``` yaml
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM

theme: minima
plugins:
  - jekyll-feed
```

EDIT:  Rendered correctly locally `bundle exec jekyll serve --watch`
