### ISSUE TITLE
The last "_" in the string is not output.

### ISSUE THREAD

**Issue by myso-kr** [jekyll/jekyll#8022]
_work_dir/_authors/2626001.md
```
---
space:
  urlId: 2626001_
  stats: ...
---
```

_work_dir/api/authors.json
```
---
layout: null
---
{
    "data": [
        {% for author in site.authors %}
        {
            "urlId": "{{ author.space.urlId }}",
            ...
        }
        {% unless forloop.last %},{% endunless %}
        {% endfor %}
    ]
}
```

localhost:4000/api/authors.json
```
{
    "data": [
        { "urlId": "2626001", ... },
        ...
    ]
]
```

**Comment by myso-kr** [comment]
??? input this....

_work_dir/_authors/2626001_.md

It disappears automatically when I write a comment?
![image](https://user-images.githubusercontent.com/1237913/75145193-d5ceac80-573b-11ea-8ead-ff61dfdf38a6.png)

**Comment by ashmaroli** [comment]
@myso-kr, YAML values with special characters or meaning need to be enclosed in quotes:
```yaml
---
space:
  urlId: "2626001_"
  stats: ...
  foo: true   # Boolean literal
  bar: "true" # String true
```
Or you risk having the value interpreted literally.
