### ISSUE TITLE
Collections defaults not applying 

### ISSUE THREAD

**Issue by limjh16** [jekyll/jekyll#8218]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | MacOS Catalina |
| `jekyll`         | Latest (4.1.0) |
| `github-pages`   | No |

---

## Expected Behaviour

Defaults set in ``_config.yml`` should apply to all markdown files in that collection.

## Current Behavior

Those defaults only apply for one file and not another

## Code Sample

[example repository](https://github.com/bozotics/bozotics.github.io/tree/wip/electronics2)

<details><summary>the relevant codes / file structure is extracted here: 
</summary>

```yaml

include:
  - _resources
collections:
  resources:
    output: true
defaults:
  - scope:
      type: resources
    values:
      layout: custom
      permalink: /resources/:title/
      other_settings: ...
...

```

```
.
├── _resources
│   ├── 2020-01-01-posta
|   |   ├── assets
|   |   └── 2020-01-01-posta.md
│   └── 2020-01-02-postb
|       ├── assets
|       └── 2020-01-02-postb.md
├── _site
|   ├── _resources
|   │   ├── 2020-01-01-posta
|   |   |   └── assets
|   │   └── 2020-01-02-postb
|   |       ├── assets
|   |       └── 2020-01-02-postb.html # This rendered html doesn't have the custom default layout applied
|   └── resources
|       └── posta
|           └── index.html
├── ...
└── _config.yml
```
</details>

Another weird thing that happens is when [paginating](https://github.com/sverrirs/jekyll-paginate-v2) the "resources" collection, postb appears with a link to ``/resources/postb/`` but it returns a 404 (since the permalink default is somehow not applied?)

I have tried moving posta.md and postb.md out of their subfolders, ``jekyll clean``, but nothing seems to work. This doesn't occur for my other collections.
