### ISSUE TITLE
jekyll --clean Ignoring Configuration File

### ISSUE THREAD

**Issue by atom0s** [jekyll/jekyll#8362]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Windows Server 2012 R2 |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

---

## Expected Behaviour

I have setup Jekyll to keep certain files in its output/dest folder such as things I do not want Jekyll to maintain:
  - Folder: downloads
  - Folder: forums
  - File: googleabc123abc123.html (A file used to verify ownership of the site.)
  - File: web.config

Expected behaviour would be the following:
  - When using `jekyll build`, keep the downloads and forums folder, and keep the google and web.config files.
  - When using `jekyll clean`, keep the downloads and forums folder, and keep the google and web.config files while clearing everything else generated.

## Current Behavior

When using `jekyll build` the two folders and web.config file are ignored properly but the google file is deleted.
When using `jekyll clean` the entire output/destination folder is deleted. The configuration is completely ignored for what to keep/ignore.

## Code Sample

The parts of my config that are relevant to this issue would be:
```yml
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - .gitignore
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - ".git"
  - ".svn"
  - "downloads"
  - "forums"
  - "private"
  - "google*.html"
  - "maintenance.php"
  - "web.config"
```
