### ISSUE TITLE
Permission error when building site in Docker

### ISSUE THREAD

**Issue by henrikx** [jekyll/jekyll#8422]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   Debian 9         |
| `jekyll`         | 4.0 |

---

## Expected Behaviour

Build new site with no errors.

## Current Behavior
When running command to build a new site `docker-compose run --rm jekyll jekyll new site`, I get the following error message, making it impossible to create a new site:
```
  Bundler: Fetching em-websocket 0.5.2Errno::EACCES: Permission denied @ rb_file_s_rename -
  Bundler: (/home/jekyll/.gem/ruby/2.7.0/cache/em-websocket-0.5.2.gem,
  Bundler: /usr/gem/cache/em-websocket-0.5.2.gem)
  Bundler: An error occurred while installing em-websocket (0.5.2), and Bundler cannot
  Bundler: continue.
  Bundler: Make sure that `gem install em-websocket -v '0.5.2' --source
  Bundler: 'https://rubygems.org/'` succeeds before bundling.
  Bundler: 
  Bundler: In Gemfile:
  Bundler: minima was resolved to 2.5.1, which depends on
  Bundler: jekyll-feed was resolved to 0.15.0, which depends on
  Bundler: jekyll was resolved to 4.1.1, which depends on
  Bundler: em-websocket
```

The same command works if I change image version to 3.8 instead of 4.0.
