### ISSUE TITLE
Jekyll don't process the files in a git submodule

### ISSUE THREAD

**Issue by wongyah** [jekyll/jekyll#8733]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     win10       |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

I import a git submodule into the jekyll directory. The submodule has markdown files only, without scss or css files in it.

I named the local subdirectory of the submodule in the underscore format "_subDirName", expecting that Jekyll will treat it as a collection folder. 

But when I tried to make links to the files in the collection (submodule), I found that none files in the submodule is included in the variable site.\<collection>.

I don't like to write another css files for the submodule. I wish it can reuse the css files in the present Jekyll directory. 

## Current Behavior

The files in a git submodule (local subdirectory of a Jekyll directory) don't be process even though I have named it with the underscore format.

### _config.yml

```
collections:
  markdown-tutorial:
    output: true
    dirtype: "tutorial"
    cnName: "Markdown 教程"
```

### Git Submodule Subdirectory

Sorry, I can't load a picture.

Here is the directory stucture:

- Jekyll Root Directory
  - doc-tec
    - _markdown-tutorial  /* This is a Git submodule */
      - some markdown files

### 

```
{%- assign pages = site.markdown-tutorial -%}
{{ pages.size }}
```

**Output: 0**

**Comment by wongyah** [comment]
I found the problem isn't caused by "git submodule". It misused the collection directory setting in _config.yml.

Now I changed my _config.yml to:

```
collections_dir: doc-tech
collections:
  markdown-tutorial:
    output: true
    dirtype: "tutorial"
    cnName: "Markdown 教程"
```

The files in git submodule gets normal now.
