### ISSUE TITLE
feat: Allow to reference (Jekyll) variables in YAML files

### ISSUE THREAD

**Issue by keunes** [jekyll/jekyll#8783]
## Summary

Make it possible to reference (Jekyll) variables (from the same or other files) in a given variable in YAML (configuration) files.

## Motivation

[My use-case](https://github.com/YoussefRaafatNasry/portfolYOU/issues/75) is that I would like to easily and quickly record my username and server of a federated service in my site's `_config` file, which the theme then can use to create different variables (e.g. my username and my profile URL) based on these, in the background.

My variables in `_config.yml`:
```
author:
  mastodon_user     : keunes
  mastodon_server   : mastodon.social # instance domain without protocol (e.g. mastodon.social)
```

The variables created by the theme, and usable in page elements:
```
social-media:
  mastodon:
    handle: @{{site.author.mastodon_user}}@{{site.author.mastodon_server}}
    profile: https://{{site.author.mastodon_server}}/@{{site.author.mastodon_user}}
```

But I think that the ability to reference variables will enable many more options in completely different contexts.

As this is a 'basic' (not 'simple', but as in 'high-level') functionality and not enabling a specific feature (e.g. an RSS feed), I believe this should be in core (not a plugin).

## Guide-level explanation

You can reference Jekyll variables in any YAML configuration file. By including a reference, its value will be 'printed' as a string or integer (depending on the source and target variables) in the new variable.

It is possible to have 'nested' references, as follows:
```
food-colours:
  fruit:
    kiwi: green
favourite:
  food: kiwi (which is {{food-colours.fruit.kiwi}})
section-titles:
  favourites: My current favourite food: {{favourite.food}}
```

If variable `C` references variable `B`, and variable `B` references variable `A`, the value of variable `A` will show in the value of variable `C` (even though variable `C` doesn't directly reference variable `A`).

Note, however, that this should not lead to vicious circles, where variables reference each-other, as here:
```
a: {{sum-b}} - {{sum-c}}
b: {{sum-a}} - {{sum-c}}
c: {{sum-a}} - {{sum-b}}
```

If such circular references occur this will lead to an error, and your site will fail to build.

## Reference-level explanation

Sorry, just got started with Jekyll, so I don't know what to write here.

## Drawbacks

There's extra functionality to maintain and create tests for. And this might be complex if people start making deeply nested variables with vicious circles. Creating helpful error messages that clearly indicate where a circular reference appears might be complicated (?)
