### ISSUE TITLE
Jekyll Cayman Theme Rouge Kramdown syntax

### ISSUE THREAD

**Issue by pippim** [jekyll/jekyll#8868]
## My Environment

Github Pages current version
## Expected Behaviour

When using Github preview the markdown syntax highlighting renders as expected:

![pippim programs md on preview](https://user-images.githubusercontent.com/92641463/139840605-beb9235e-3db6-455c-b5c8-6118fc0ed0fa.png)

## Current Behavior

When published the first two lines take up the whole screen shot (extra lines added after each element) and the font is tiny:

![pippim programs md published](https://user-images.githubusercontent.com/92641463/139840805-c78677eb-f7b2-4422-b93d-420329c1729b.png)

## Code Sample

Public repo: https://github.com/pippim/pippim.github.io/blob/main/programs.md

`_config.yml`:

``` yml
theme: jekyll-theme-cayman
title: Pippim - Free Software
description: Free open-source software for the World. Free of Ads too!
kramdown:
  input: GFM
  syntax_highlighter: rouge
```
