### ISSUE TITLE
[Bug]: no page after build

### ISSUE THREAD

**Issue by santimirandarp** [jekyll/jekyll#9014]
Followed this tutorial at your site: https://jekyllrb.com/docs/continuous-integration/github-actions/

line by line. The built says is succeded and the github page branch is created, but there is no page whatsoever, and no html files either.

Is there an error in the example? 

### Action 
```
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
