### ISSUE TITLE
[Bug]: default scope in jekyll 4.2.2 not working

### ISSUE THREAD

**Issue by Zxce3** [jekyll/jekyll#9104]
### Operating System

Ubuntu 20.04

### Ruby Version

ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

### Jekyll Version

jekyll 4.2.2

### GitHub Pages Version

latest

### Expected Behavior

everything works only the default scope can't

### Current Behavior

everything works only the default scope can't, I want to make a scope like below
```yml
defaults:  
  -
      scope:
        path: '_learning'
        type: learn
      values:
        layout: learn
        permalink: /learn/:title/
```
can only be solved by collection for permalink and the folder must be `_learn` and cannot be `_learning` unlike the one in the default scope setting

```yml
collections:
  learn:
    output: true
    sort_by: order
    permalink: /learn/:title/
```

I'm using jekyll version 4.2.2 with liquid version 4.0 and I've also read some of the issues below

- https://github.com/jekyll/jekyll/issues/3287
- https://github.com/jekyll/jekyll/issues/4458
- https://github.com/jekyll/jekyll/issues/4331

and it looks like this is a bug
