### ISSUE TITLE
Incremental Build | Use Hash instead of Modification Time

### ISSUE THREAD

**Issue by DER-SSt** [jekyll/jekyll#9149]
### Motivation
I am trying to use the [incremental build](https://jekyllrb.com/docs/configuration/incremental-regeneration/) in a Gitlab-CI-runner. 
After every push the website should be incrementally rebuild.

### Problem
When the runner checks the project out, every file has the current time as modification time. Since Jekyll detects changes based on the modification time, this leads to a full rebuild every time.

### Proposed Solution
Hash input files and store the hash in `.jekyll-metadata`. 
Ignore the modification time completely.

### Gitlab Runner Configuration
```yaml
ci_build_job:
  cache:
    paths:
      - _site/
      - .jekyll-metadata
  script:
    - stat Gemfile   # prints Modification Time
    - jekyll build --incremental
```

### Show that Modifcation Time is used by jekyll --incremental
Tested with [jekyll/jekyll:4.2.2](https://hub.docker.com/layers/jekyll/jekyll/4.2.2/images/sha256-6859f3af91550c7d5935ac97e82d586dad4c67a0577b5484b9303e41565687ef?context=explore)
```bash
jekyll new inctest
cd inctest/
jekyll build --incremental --profile  # Full build
jekyll build --incremental --profile  # Incremental build

find . -type f -exec touch {} +       # Change Modification Time of all files
jekyll build --incremental --profile  # Full build, should be incremental
```
