### ISSUE TITLE
[Bug]: Create collections/_cupcakes folder when building my Jekyll site with CI/CD

### ISSUE THREAD

**Issue by csharpee** [jekyll/jekyll#9193]
### Operating System

linux ruby:latest

### Ruby Version

3.1.2

### Jekyll Version

4.2.2

### GitHub Pages Version

NA

### Expected Behavior

When collections/**_cupcakes** folder is added to *_config.yml* create custom folder on *bundle exec jekyll build --verbose --trace* aka jekyll build.

I ran into a troublesome bug, maybe I am doing something wrong here, but on my CI/CD, I kept getting an error and couldn't pin point it down because the **collections/_posts** folder was being created without any trouble, but the **_cupcakes** folder and files kept populating the error: 

```
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)

<internal:dir>:98:in `open': No such file or directory @ dir_initialize - ./collections/_cupcakes/ (Errno::ENOENT)
```
I am able to manually create this folder with Ruby, but shouldn't Jekyll do this? 

### Current Behavior

```
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)

<internal:dir>:98:in `open': No such file or directory @ dir_initialize - ./collections/_cupcakes/ (Errno::ENOENT)
```

### Relevant log output

```shell
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)

<internal:dir>:98:in `open': No such file or directory @ dir_initialize - ./collections/_cupcakes/ (Errno::ENOENT)
```

### Code Sample

My _config.yml snippet: 

```
# Collection configuration
# These collections will sort types of products and loop through that
# type to be displayed on a page. As an example, I have 10 "3D" items, all 10 items
# will be displayed when a category is selected on the product main index page.
collections_dir: collections

collections:
  products:
    output: true # true or false
    permalink: /products/:path/
 ```

**Comment by csharpee** [comment]
Doing something like this manually has resolved the conflict, but maybe my _config.yml is funky? 

```
      # manually create custom collection folders [bug: shouldn't Jekyll do this? https://github.com/jekyll/jekyll/issues/9193]
      if not Dir.exist?("./collections/_products")
        Jekyll.logger.info "the Jekyll products directory does not exist, let's create one".to_s.red
        Dir.mkdir("./collections/_products/")
        Jekyll.logger.info "DIR DEBUG: The local ./collections/_products directory is created at: ./collections/_products/".to_s.yellow
      end
```

**Comment by ashmaroli** [comment]
@csharpee Custom collections behave *slightly different* from `_posts`. So, the latter shouldn't be used as a reference point.

Moreover, Jekyll does not *create* source files out of the box. It simply *reads* existing file paths within the *source* directory. This behavior gets enhanced with the use of plugins (e.g. `Jekyll::Generator` based plugins).

For Jekyll to *read* and output a certain custom collection, it has to be explicitly declared in the config setting.
Therefore, the following is necessary for Jekyll to know `_cupcakes` is a collection:

```yaml
collections:
  cupcakes:
    output: true # Needed to generate `./_site/cupcakes/**/*.html` paths.
```
