### ISSUE TITLE
[Bug]: Updating to 4.3.2 + Ruby 3.2.0 broken by google-protobuf?

### ISSUE THREAD

**Issue by buddhist-uni** [jekyll/jekyll#9294]
### Operating System

Ubuntu

### Ruby Version

ruby 3.2.0 (2022-12-25 revision a528908271) +YJIT [x86_64-linux]

### Jekyll Version

4.3.2

### Expected Behavior

Attempting to upgrade Jekyll to 4.3.2 in the hopes that this version will be compatible with Ruby 3.2.0

### Current Behavior

changed jekyll version to 4.3.2 in my Gemfile and ran `bundle update jekyll`  Got an error from Google Protobuf saying that its incompatible with Ruby 3.2 :\

### Relevant log output

```shell
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
google-protobuf-3.21.12-x86_64-linux requires ruby version < 3.2.dev, >= 2.5, which is incompatible with the current
version, ruby 3.2.0p0
```

**Comment by ntkme** [comment]
Known issue in google-protobuf. See: https://github.com/protocolbuffers/protobuf/issues/11538

**Comment by buddhist-uni** [comment]
Thanks @ntkme - There was a PR merged to fix that three weeks ago... What still needs to happen before `bundle update jekyll` Just Works™️?

**Comment by ntkme** [comment]
Try `gem update --system` and run latest bundler, which should be able to correctly fallback to platform ruby and get it installed.

**Comment by buddhist-uni** [comment]
Ah! Thanks 😅 That's indeed what I was missing 😊 Thanks! 🙏

**Comment by fernandopasik** [comment]
Thank you @ntkme for the suggestion there, it worked well. My 2 cents is if you are using the github action `ruby/setup-ruby@v1` don't forget to remove the option `bundler-cache: true` and  do a manual install after the gem update.

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3'
  - name: Update Gem
    run: gem update --system
  - name: Install Gems
    run: bundle install
```
