### ISSUE TITLE
[Bug]: Step-by-step Tutorial not working as expected

### ISSUE THREAD

**Issue by Lyatt77** [jekyll/jekyll#9611]
### Operating System

Ubuntu Shell, Windows 11

### Ruby Version

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

### Jekyll Version

jekyll 3.9.5

### GitHub Pages Version

github-pages 231

### Expected Behavior

Looking to see sitemap, seo tag and jekyll feed plugins display functionality. 

### Current Behavior

At the moment, when I run `bundle exec jekyll serve` as I am told to in the tutorial, I am show then exact same website that I had in the previous steps. 

### Code Sample

Here is a copy of the files that are relevantly changed
My Gemfile
```
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "github-pages", "~> 231"

gem "webrick", "~> 1.8"

group :jekyll_plugins do
    gem "jekyll-sitemap"
    gem "jekyll-feed"
    gem "jekyll-seo-tag"
end
```

My config file 
```
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default" 


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
```

My default layout
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page.title }}</title>
    <link rel="stylesheet" href="/assets/css/styles.css">
    {% feed_meta %}
    {% seo %}
  </head>
  <body>
    {% include navigation.html %}
    {{ content }}
  </body>
</html>
```

Please let me know if I'm missing something. 
Thanks
