### ISSUE TITLE
[Bug]: keep_files in _config.yml breaks building

### ISSUE THREAD

**Issue by gusborg88** [jekyll/jekyll#9677]
### Operating System

Windows 11

### Ruby Version

ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.3.3

### GitHub Pages Version

Latest

### Expected Behavior

the site should be able to build with keep_files in _config.yml

### Current Behavior

I did `bundle exec jekyll serve --trace`
It works when i take out keep_files, but otherwise it breaks
i've tried setting it to `play.bat`, `"play.bat"`, `"assets/"`, etc

### Relevant log output

```shell
Configuration file: C:/Users/Gus/SavedGames/FNF-Web-Engine/_config.yml
            Source: source
       Destination: build
 Incremental build: enabled
      Generating...
jekyll 3.10.0 | Error:  undefined method `map' for an instance of String
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/cleaner.rb:96:in `keep_dirs': undefined method `map' for an instance of String (NoMethodError)

      site.keep_files.map { |file| parent_dirs(site.in_dest_dir(file)) }.flatten.to_set
                     ^^^^
Did you mean?  tap
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/cleaner.rb:44:in `existing_files'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/cleaner.rb:25:in `obsolete_files'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/cleaner.rb:15:in `cleanup!'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:201:in `cleanup'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:72:in `process'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-3.10.0/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby33-x64/bin/jekyll:32:in `load'
        from C:/Ruby33-x64/bin/jekyll:32:in `<main>'

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### Code Sample

_config.yml
```yml
title: FNF Web Engine
description: #i took out this part
url: http://127.0.0.1
port: 8080
source: source
destination: build
layouts_dir: source/layouts
keep_files: play.bat

exclude:
  - jekyll.bat
  - docs/
  - Gemfile
  - Gemfile.lock
  - bundle
  - .gitignore
  - README.md
  - FNF-Web-Engine.code-workspace

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      title: Untitled page?
      permalink: :basename

webrick:
  headers:
    Cache-Control: max-age=604800
```
gemfile (without comments)
```gemfile
source "https://rubygems.org"
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
gem "bigdecimal", "~> 3.1.8"
gem "base64", "~> 0.2.0"
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```
