### ISSUE TITLE
[Bug]: Permalink patterns changed/broken between Jekyll 4.3.4 and 4.4.0

### ISSUE THREAD

**Issue by jonsage** [jekyll/jekyll#9761]
### Operating System

Debian GNU/Linux 12 (bookworm)

### Ruby Version

ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]

### Jekyll Version

jekyll 4.4.0

### GitHub Pages Version

Latest

### Expected Behavior

I had expected the permalink formats to operate the same way between 4.3.4 and 4.4.0, however instead of the expected paths of:

```
/hello/world/index.md -> /hello/world/index.html
/hello/world.md -> /hello/world/index.html
```

### Current Behavior

I'm now getting:

```
/hello/world/index.md -> /hello/world/index/index.html
/hello/world.md -> /hello/world/index.html
```

Notice the extra `/index/` folder in the path.

These are paths generated from pages in collections using the following config rules, which up until 4.4.0 were producing the expected output:

```yaml
permalink: pretty

collections:
  pages:
    output: true
  posts:
    output: true
  guides:
    output: true
  reference:
    output: true

defaults:
  - scope:
      path: "_*/**/*"
    values:
      permalink: /:categories/:collection/:path:output_ext
      layout: page
  - scope:  
      path: "_*/**/*.md"
    values:
      permalink: /:categories/:collection/:path/
  - scope:  
      path: "_*/**/index.md"
    values:
      permalink: /:categories/:collection/:path:output_ext
```

### Relevant log output

```shell

```
