### ISSUE TITLE
feat: post_url accept liquid variable as input

### ISSUE THREAD

**Issue by jeffque** [jekyll/jekyll#9775]
## Summary

As `{% link {{ somevar }} %}` tag that accepts a Liquid variable as value, allow passing Liquid variables (and thus expansions) to `{% post_url %}`

## Motivation

`post_url` tag works only for constants, treating any argument as plain constant. I can benefit adding metadata pointing to my own posts. For instance, I always create an article about some change in my blog.

So, if I can list for some behavior a list of my own blog posts and show it to me, that would be of great value.

## Guide-level explanation

Let us have a list of blog posts from our own to show, a list of slugs/titles named `my_posts`, with the content:

```yaml
my_posts:
- title: "Post facilmente citável"
  slug: 2024-05-22-citable
- title: "Alpine morreu! Vida longa ao Alpine!"
  slug: 2025-02-03-long-live-alpine
- title: "Fluent Builder com região crítica"
  slug: 2021-12-23-fluent-builder
```

We can iterate through this list and create links:

```liquid
Check these posts for further explanation:

{% for posts in my_posts %}
- [{{ post.title }}]({% post_url {{ post.slug }} %})
{% endfor %}
```

## Reference-level explanation

It will deal with the input for `post_url` tag as a Liquid string, just as in the `link` tag.

## Drawbacks

The validation will be at `render` level instead of at initialization level.

It may cause some overhead to run `post_url` as it deals with Liquid rendering to get the post slug.

Users that relies having `{{` in their post urls and link them back using `{% post_url %}` may experience some backlash with this change.

## Unresolved Questions

What will be such overhead?

**Comment by jeffque** [comment]
Some use I am doing for my blog:

- `_data/meta.yaml`

```yaml
variables:
  - name: computaria-link-edit
    description: "Permite a edição viva"
    env: development
    posts: [ { title: "Link edit", slug: "2025-02-15-link-edit"} ]
  - name: computaria-cite
    description: "Copiar referência fácil"
    env: '*'
    posts: [ { title: "Citável", slug: "2024-05-22-citable" }, { title: "Link edit", slug: "2025-02-15-link-edit"} ]
```

Page:

```liquid
<style>
    table.lalala {
        border: 1px solid gray;
        width: 90%
    }
    table.lalala tr {
        /* width: 90% */
    }
    table.lalala th {
        border: 1px solid gray;
        font-weight: bold;
    }
    table.lalala td {
        border: 1px solid gray;
    }
</style>

Hmmm, teste? {{jekyll.environment}}

<table class='lalala'>
    <tr>
        <th>Variável</th><th>Descrição</th><th>Valor</th><th>Posts</th>
    </tr>
    <tbody>
        {% for var in site.data.meta.variables -%}
        {% if var.env == '*' or var.env == jekyll.environment %}
        <tr>
            <td>{{ var.name }}/{{ var.env }}</td><td>{{ var.description }}</td>
            <td></td>
            <td>
                {% if var.posts.size > 0 %}
                <ul>
                {% for bg_post in var.posts %}
                    <li><a href="{% post_urlwa {{ bg_post.slug }} %}">{{ bg_post.title }}</a></li>
                {% endfor %}
                </ul>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
```

Rendering:

<img width="684" alt="print of the above liquid code rendered" src="https://github.com/user-attachments/assets/34a7c451-1745-40e0-a40b-9088fd00dab4" />


HTML generated for the table:

```html
<table class="lalala">
    <tbody><tr>
        <th>Variável</th><th>Descrição</th><th>Valor</th><th>Posts</th>
    </tr>
    </tbody><tbody>
        
        <tr>
            <td>computaria-link-edit/development</td><td>Permite a edição viva</td>
            <td></td>
            <td>
                
                <ul>
                
                    <li><a href="/blog/2025/02/15/link-edit">Link edit</a></li>
                
                </ul>
                
            </td>
        </tr>
        
        
        <tr>
            <td>computaria-cite/*</td><td>Copiar referência fácil</td>
            <td></td>
            <td>
                
                <ul>
                
                    <li><a href="/blog/2024/05/22/citable">Citável</a></li>
                
                    <li><a href="/blog/2025/02/15/link-edit">Link edit</a></li>
                
                </ul>
                
            </td>
        </tr>
        
        
    </tbody>
</table>
```
